### ISSUE TITLE
More robust myelin separation algorithm

### ISSUE THREAD

**Issue by alzaia** [axondeepseg/axondeepseg#100]
So far, I experimented with distance transform + watershed, but it is only robust on samples with low axon density (less compact fibers) and/or neighbour myelin sheaths that have a low overlap between them. 

The ongoing dev on this is under the ```dev_myelin_separation``` branch, in the following notebook:
https://github.com/neuropoly/axondeepseg/blob/dev_myelin_separation/notebooks/myelin_separation.ipynb

**Comment by mathieuboudreau** [comment]
Stale / partly done by @hermancollin  recently
