### ISSUE TITLE
Update contribution guideline

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#105]
we need to establish conventions on PR titles and description. We could get inspiration from: https://github.com/neuropoly/spinalcordtoolbox/wiki/Contribution-Guidelines#submit-a-pull-request

**Comment by alzaia** [comment]
Is this OK?
https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution#procedure-to-submit-a-pull-request-pr-for-new-devfeaturesimplementations

**Comment by jcohenadad** [comment]
> You can add labels that describe the category and type of the change. A change can have multiple types if it is appropriate but it can only have one category.

unclear what is category and what is type

**Comment by alzaia** [comment]
Ok, I changed that sentence to this one:
```
You can add labels that describe the type of the proposed PR (e.g. bug, enhancement, duplicate).
```

**Comment by jcohenadad** [comment]
not great-- to vague and implies maintenance-- i've made the following changes:
- created single colored labels and added "category" in the name for [easy referencing](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution#procedure-to-submit-a-pull-request-pr-for-new-devfeaturesimplementations)
- updated the [wiki](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution#procedure-to-submit-a-pull-request-pr-for-new-devfeaturesimplementations)
- in the future we will be able to use the category for [creating CHANGELOG automatically](https://github.com/neuropoly/spinalcordtoolbox/blob/master/install/sct_changelog.py)

**Comment by jcohenadad** [comment]
Suggestion: modify this version: https://github.com/neuropoly/spinalcordtoolbox/blob/master/CONTRIBUTING.rst
Remove the duplication on the wiki

**Comment by mariehbourget** [comment]
Hi @jcohenadad , I realised after changing category labels that the "category:" string was use in the wiki for easy referencing in guidelines for contributions: https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution).
Would you prefer I update the wiki in some way or go back to the labels with “category:”? Thanks!

**Comment by jcohenadad** [comment]
> Hi @jcohenadad , I realised after changing category labels that the "category:" string was use in the wiki for easy referencing in guidelines for contributions: https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution).
> Would you prefer I update the wiki in some way or go back to the labels with “category:”? Thanks!

Please update the wiki

**Comment by mariehbourget** [comment]
For now, I wrote the “category” string in the description of the labels instead of in their names. It keeps the wiki clean and preserves the easy referencing.

**Comment by jcohenadad** [comment]
@mariehbourget, ok i feel we have too many categories now, and also there is a mix between "type" and "context". For example, both "bug" and "GUI" are now categories, but in fact we could have a bug in the GUI, meaning that both labels would be needed. In fact, we need to separate type and context. This will be helpful to create changelogs that look like [this](https://github.com/neuropoly/spinalcordtoolbox/blob/master/CHANGES.md) (generated automatically thanks to appropriate labeling). 

So, i suggest something like this (based on your suggestions during the meeting):

CATEGORIES (color: #5319e7):
- Bug
- Documentation
- Enhancement
- Feature
- Refactoring

CONTEXT (color: #d4c5f9):
- Augmentation
- GUI
- Installation
- Models
- Patching
- Processing
- Training

OTHER
- Question
- WIP
...

**Comment by mariehbourget** [comment]
Thanks for your feedback.
I’ve made the changes. From the list above, I moved Refactoring to “context” and Installation to “category”. I also added Testing to “category”. This is consistent with Wiki guidelines and with the sct changelog example.

**Comment by joshuacwnewton** [comment]
Two things:

* This issue covers similar territory to #359.
* In recent months, SCT/ivadomed/shimming-toolbox have adopted pull request templates all based on the same requirements. 

So, I could quickly add this same PR template to ADS to address this issue, then leave remaining discussion for #359?

**Comment by mathieuboudreau** [comment]
Stale, more recent is #359
