### ISSUE TITLE
Predicting touching areas to improve watershed

### ISSUE THREAD

**Issue by perone** [axondeepseg/axondeepseg#108]
There is a very nice approach [here](https://github.com/ternaus/TernausNetV2) where they predict not only the pixel-level classes but the touching areas as well, so it can be used to improve the seed for the watershed. I think this can be a good idea for AxonDeepSeg. There is [notebook here](https://github.com/ternaus/TernausNetV2/blob/master/Demo.ipynb) as well.

PS: I added this as an issue but it is just an idea for the future.

**Comment by jcohenadad** [comment]
Related to: https://github.com/neuropoly/axondeepseg/issues/211 https://github.com/neuropoly/axondeepseg/issues/384

**Comment by mathieuboudreau** [comment]
Stale
