### ISSUE TITLE
BUG: fail in call to axon_segmentation from apply_model.py when no element is detected

### ISSUE THREAD

**Issue by oumayb** [axondeepseg/axondeepseg#130]
When trying to apply a trained model using the `axon_segmentation` function from the `apply_model.py` file on a test image, this message error appears sometimes.
Could it be because the model applied hasn't learned enough? In that case, shouldn't the function just create a mask image with only background, and not try to generate myelin and axon masks?

The applied model:
https://drive.google.com/drive/folders/1BX-VgOFxGGzEYtfOQWDox3s0a7v9cpQL?usp=sharing

The test image
![956](https://user-images.githubusercontent.com/20790171/44484336-8590fe80-a61b-11e8-9b49-1463efb0f35d.png)

The used config file
https://drive.google.com/open?id=15-kcAF3m-rzYmuVEaNESVWOg3hy_ZIIh

Loading acquisitions ...
Rescaling acquisitions to the target resolution ...
Graph construction ...
Beginning inference ...
processing patch 1 of 6
processing patch 2 of 6
processing patch 3 of 6
processing patch 4 of 6
processing patch 5 of 6
processing patch 6 of 6
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-132c9c93bc2e> in <module>()
      5                                       config_dict=config_mikula,
      6                                       verbosity_level=3,
----> 7                                       resampled_resolutions=0.02)

~/axondeepseg/AxonDeepSeg/apply_model.py in axon_segmentation(path_acquisitions_folders, acquisitions_filenames, path_model_folder, config_dict, ckpt_name, segmentations_filenames, inference_batch_size, overlap_value, resampled_resolutions, acquired_resolution, prediction_proba_activate, write_mode, gpu_per, verbosity_level)
    275 
    276 
--> 277                         axon_prediction, myelin_prediction = get_masks(os.path.join(path_acquisitions_folders[i], segmentations_filenames[i]))
    278 
    279 

~/axondeepseg/AxonDeepSeg/visualization/get_masks.py in get_masks(path_prediction)
     27         tmp_path[0] = os.path.splitext(tmp_path[0])[0]
     28 
---> 29     imageio.imwrite(tmp_path[0] + '_seg-axon.png', axon_prediction.astype(int))
     30     imageio.imwrite(tmp_path[0] + '_seg-myelin.png', myelin_prediction.astype(int))
     31 

~/miniconda3/lib/python3.6/site-packages/imageio/core/functions.py in imwrite(uri, im, format, **kwargs)
    244     writer = get_writer(uri, format, 'i', **kwargs)
    245     with writer:
--> 246         writer.append_data(im)
    247 
    248     # Return a result if there is any

~/miniconda3/lib/python3.6/site-packages/imageio/core/format.py in append_data(self, im, meta)
    490             im = asarray(im)
    491             # Call
--> 492             return self._append_data(im, total_meta)
    493 
    494         def set_meta_data(self, meta):

~/miniconda3/lib/python3.6/site-packages/imageio/plugins/pillow.py in _append_data(self, im, meta)
    329                 im = image_as_uint(im, bitdepth=16)
    330             else:
--> 331                 im = image_as_uint(im, bitdepth=8)
    332             PillowFormat.Writer._append_data(self, im, meta)
    333 

~/miniconda3/lib/python3.6/site-packages/imageio/core/util.py in image_as_uint(im, bitdepth)
    109             raise ValueError('Maximum image value is not finite')
    110         if ma == mi:
--> 111             raise ValueError('Max value == min value, ambiguous given dtype')
    112         _precision_warn(dtype_str1, dtype_str2,
    113                         'Range [{}, {}].'.format(mi, ma))

ValueError: Max value == min value, ambiguous given dtype

**Comment by mathieuboudreau** [comment]
@oumayb have you been experiencing this mostly in the Python 3.6 branch, or have you ever experienced it before while using Python 2.7?

**Comment by oumayb** [comment]
@mathieuboudreau I've experienced it before while using Python 2.7.

**Comment by jcohenadad** [comment]
I've run into the same issue on py3k (with commit d330de2b35979b4d0fcf13ecef5600f53edabf6d).

**Comment by mathieuboudreau** [comment]
Closing, issue no longer exists currently.
