### ISSUE TITLE
Better management of RAM during resampling

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#138]
During resampling, if data is too large for the RAM, it starts swapping until available HD storage is reached, leading the station to lamentably crash (not enough free space to run the OS). 

To reproduce:
data: https://osf.io/28k4m/
syntax (note: the value `-s 1` is purposely wrong to make the system crash): 
~~~
axondeepseg -t TEM -i Does_Kelm_072214_021.tif -v 2 -s 1
~~~

Here's what happened to my poor 16GB RAM and 30GB ROM OSX (p.s. swap would have continued until "the end" unless i manually close the Terminal window):

![screen shot 2018-10-23 at 15 15 11](https://user-images.githubusercontent.com/2482071/47385195-58be9d80-d6d7-11e8-80a7-73917cf2033e.png)

Possible avenues:
- knowing the image size and resolution, calculate what would be the required RAM and assess if possible based on the system config (RAM+available disk space).
- Make it possible to use CTRL+Z to quit (currently not possible-- I had to close the Terminal to stop the Python process).

**Comment by mathieuboudreau** [comment]
That makes sense! We handled the case for too small pixel sizes, it's logical to do so for too large. What's happening here is that it's resampling the image to a standard size (I think about 0.001 for TEM), so if you say your pixel sizes are 1, it will try and divide each by 1000x1000, certainly causing a memory overflow. 

I agree with both your proposed avenues (though I'm not sure why your second point wasn't possible), but it would also make sense to set "logical" max pixel sizes for each modality (i.e. is it even possible for TEM to measure at 1 micrometer resolutions?).

**Comment by jcohenadad** [comment]
i would not venture into assessing what's a "logical max pixel size", because ADS might evolve towards a typical use-case where users would train a model for their own data and then use ADS with their model (i.e. we loose the concept of SEM/TEM).

**Comment by mathieuboudreau** [comment]
Ok - although, the CLI interface has a lot of SEM/TEM details hardcoded already – but that's another story. 

I still think there should be some kind of upper limit where we at least give the user a warning message saying "Hey, are you sure you meant to input this pixel size? The units we assume are in micrometer" – it's a lot more useful if they made a typo than just checking the users maximum allowable RAM and allowing them to segment their images with a likely incorrect pixel size.

**Comment by mathieuboudreau** [comment]
Stale
