### ISSUE TITLE
AxonDeepSeg Refactoring

### ISSUE THREAD

**Issue by perone** [axondeepseg/axondeepseg#141]
**PS: this will be discussed in the meeting on 07 Nov 18.**

AxonDeepSeg nowadays has a very complex codebase, specially for the model definition where the TensorFlow low-level API is being used. What we want to do is to simplify some things to reduce the amount of complexity and code from the codebase.
One ideia is to migrate the code to use either Keras or PyTorch. This would be a change that will of course reuse the data loading mechanisms (image loading, patching, etc), but it might need some rework to make the dataset suitabe for each framework (Keras/PyTorch for example).
With that done, it would easier and faster to exchange the model for another model for the sake of experimentation, improvement, etc.

Some things to consider:
- Should we go for PyTorch or Keras ?
- Are there any other issues we want to address in this refactoring ?
- What should be the use case for the users ? Should they be able to easily fine-tune the model with their data ? Should we fine-tune for them ? Due to the variability in images, I don't see much that can be done if not by fine-tuning on at least some patches of new data (which can be selected by active learning, the field that @MelanieLu is working);
- Should we have a developer documentation (Sphinx) for newly developed code ?

If you have more points to consider or any other comments, please edit this issue or comment below.

**Comment by mathieuboudreau** [comment]
>Are there any other issues we want to address in this refactoring ?

Right now, some of the code is hardcoded very specifically for SEM/TEM (e.g. see below some examples). I think identifying where these occur, and how these can be generalised/extended for any new model we want to introduce, might also worth exploring during this refactoring.

https://github.com/neuropoly/axondeepseg/blob/476bb3fcf1a5092514c4c73d124a8e9f46d6015b/AxonDeepSeg/data_management/dataset_building.py#L126-L131

https://github.com/neuropoly/axondeepseg/blob/9e59f536da6c709d0341999ae2b11945de588cb2/AxonDeepSeg/segment.py#L221-L237

**Comment by mathieuboudreau** [comment]
Closed, stale.
