### ISSUE TITLE
No matching distribution found for tensorflow==1.3.0

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#143]
using 2bee818b5be963b11f57733b110f1818daebf402 on `rosenberg`, i cannot properly install tensorflow==1.3.0: 
~~~
[...]
Collecting tensorflow==1.3.0 (from AxonDeepSeg==2.2.dev0)
  Could not find a version that satisfies the requirement tensorflow==1.3.0 (from AxonDeepSeg==2.2.dev0) (from versions: )
No matching distribution found for tensorflow==1.3.0 (from AxonDeepSeg==2.2.dev0)
(venv_ads) [jcohen@rosenberg axondeepseg]$ pip install tensorflow==1.3.0
Collecting tensorflow==1.3.0
  Could not find a version that satisfies the requirement tensorflow==1.3.0 (from versions: )
No matching distribution found for tensorflow==1.3.0
(venv_ads) [jcohen@rosenberg axondeepseg]$ pip -V
pip 18.1 from /home/jcohen/miniconda3/envs/venv_ads/lib/python3.7/site-packages/pip (python 3.7)
(venv_ads) [jcohen@rosenberg axondeepseg]$ python
Python 3.7.1 (default, Oct 23 2018, 19:19:42) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
~~~

**Comment by mathieuboudreau** [comment]
@jcohenadad I hit this issue too, but I don't remember what exactly solved it. As you can see, I think your virtual environment actually doesn't find any available versions for tensorflow (`(from versions: )`).  Feel free to try to install any other version (our previous one was 1.9.0) to see if it'll install, but I think not.

Did you create your virtual environment with `conda` or `virtualenv`?

**Comment by jcohenadad** [comment]
> Did you create your virtual environment with conda or virtualenv?
i used conda

**Comment by jcohenadad** [comment]
~~~
(venv_ads) [jcohen@rosenberg axondeepseg]$ pip install tensorflow==1.9.0
Collecting tensorflow==1.9.0
  Could not find a version that satisfies the requirement tensorflow==1.9.0 (from versions: )
No matching distribution found for tensorflow==1.9.0
~~~

:-(

**Comment by jcohenadad** [comment]
note: i'm on miniconda (not anaconda)

**Comment by mathieuboudreau** [comment]
Yeah, I haven't been able to create a good virtualenv with conda yet on Rosenberg. Maybe @perone can chime in again.

The virtual environment steps that ended up working for me last week (passing pip installation & passing unit tests) were:

* Go to the user's home directory `~`
* `python3.6 -m virtualenv venv_ads`
* `source venv_ads/bin/activate`

**Comment by mathieuboudreau** [comment]
@jcohenadad Ah ha, yes, when I tried installing with conda, I was using miniconda too. That might be part of the problem.

**Comment by jcohenadad** [comment]
i would like to explore possibilities with miniconda, because it is much lighter (not for me, but for potential ADS users). Maybe the issue is related to 3.7 (https://github.com/tensorflow/tensorflow/issues/17022#issuecomment-435357209). Exploring...

**Comment by mathieuboudreau** [comment]
Ahh yes, I think that's how I got around it too. Your venv/miniconda is using 3.7.1, there's no tensorflow versions available for that Python 3.7.

**Comment by jcohenadad** [comment]
yup! i confirm: it's a 3.7 issue. Works with 3.6

**Comment by jcohenadad** [comment]
we should definitely update the doc and provide a step-by-step installation with (mini)conda.

**Comment by Stoyan-I-A** [comment]
I have this issue. I tried to install tensorflow 1.3.0 and 1.9.0 on the machine at Poly and it didn't work. I am using Python 3.6.1. Perhaps I need a slightly newer version of Python.

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A did you first install miniconda and then create & activate a virtual environment? The doc details those steps: https://axondeepseg.readthedocs.io/en/latest/documentation.html#installation

**Comment by Stoyan-I-A** [comment]
I just installed miniconda and created a virtual environment of Python 3.6.5 and it's still not working.

**Comment by mathieuboudreau** [comment]
Did you also do the venv activation step? `conda activate (name of your venv)`? If so, maybe we should schedule a video call so I can see your screen in real-time.

**Comment by Stoyan-I-A** [comment]
@mathieuboudreau I tried with Stoyan to reproduce the installation steps on the doc, and I confirm that the issue is present. More details:
OSX: 10.10.5
conda 4.5.12
Python 3.6.8 (from: `conda create -n ads_venv python=3.6`)

Maybe this is related to recent updates in miniconda. We should find a solution asap.

**Comment by mathieuboudreau** [comment]
Could you check the version and location of your pip tool? `pip -V`

Mine is 19.0.1, and is located in a subfolder of my venv folder.

Python 3.6.8 works fine for me, and I am using conda 4.5.11 on Rosenberg.

**Comment by mathieuboudreau** [comment]
Otherwise, it may be that Stoyans OSX version is too old (see https://www.tensorflow.org/install for compatible OS versions)

**Comment by jcohenadad** [comment]
> Otherwise, it may be that Stoyans OSX version is too old (see https://www.tensorflow.org/install for compatible OS versions)
Ah! it's likely the problem then ;-)  Good call @mathieuboudreau and @Stoyan-I-A (who suggested that possibility to me).

**Comment by Stoyan-I-A** [comment]
Update : 
I found this thread on stackoverflow
https://stackoverflow.com/questions/38896424/tensorflow-not-found-using-pip?page=1&tab=votes#tab-top
I was able to install any version of tensorflow by changing the number on the command

**Comment by jcohenadad** [comment]
@Stoyan-I-A are you talking about this command?
~~~
python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl
~~~

**Comment by Stoyan-I-A** [comment]
yes

**Comment by jcohenadad** [comment]
ok. In any case we should probably update the doc to mention about the OS version limitation. @mathieuboudreau @perone should we give the possibility to use older OS version and have a wheel install, or should we just support recent OS versions?

**Comment by mathieuboudreau** [comment]
>@mathieuboudreau @perone should we give the possibility to use older OS version and have a wheel install, or should we just support recent OS versions

So if I understand correctly, @Stoyan-I-A circumvented Tensorflow's OS version check by directly downloading the pip wheel for the specific Tensorflow version he wanted? I don't think we should support that, as there must be a reason why Tensorflow set that OS limit. @perone ?

If we do, then it should be given in a "Warning" box in the doc, and say that we don't know how well this will work and won't support bugs that the user encounters using this setup (and highly suggest that they upgrade their OS, if possible...).

**Comment by jcohenadad** [comment]
As @mathieuboudreau mentioned, I would also lean towards not supporting older OS, simply because we don't have the bandwidth. Also I would be more aggressive than just showing a "warning" (that only 10% people will see, and those who will see it will forget its existence 5min later). 

Instead, I would check for the platform during installation, and if it does not fit OS specs, I would exit install with error, saying that "OS is not supported, please install more recent version, see doc: URL_DOC".

**Comment by Evans-Okerosi** [comment]
I encountered the same issue while using anaconda with python 3.7.1. I was able to resolve it by creating a new conda virtual env with python 3.6

**Comment by mathieuboudreau** [comment]
Thanks for the note @Evans-Okerosi ! We do in fact specify in the documentation ([here](https://axondeepseg.readthedocs.io/en/latest/documentation.html#virtual-environment)) to use a virtual environment with Python 3.6. Did you install using `pip`? That's always been a worry of mine; users installing using that command are likely to miss the documentation that we post on GitHub.

**Comment by mdiktushar** [comment]
pip install tensorflow==1.3.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.3.0
ERROR: No matching distribution found for tensorflow==1.3.0

how can I get TensorFlow 1.3.0?

**Comment by Stoyan-I-A** [comment]
@mdiktushar I assume you found this issue by searching the error message on Google. Unfortunately, we can't really help you with tensorflow 1.3.0 as we currently use a newer version (1.13.1) with our software.

**Comment by mathieuboudreau** [comment]
Closed - Tensorflow is not used anymore since ivadomed.
