### ISSUE TITLE
Wrapper for patching

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#145]
Currently the patching is integrated into ADS training/inference pipeline and is hard to run in isolation. The idea would be to create a function that can be called via terminal, e.g.:
~~~
axondeepseg_patch --input IMAGE --output FOLDER
~~~

more info in this notebook: https://github.com/neuropoly/axondeepseg/blob/2b2a15bae2040fa0969cf027a127254af82523be/notebooks/guide_dataset_building.ipynb

**Comment by mathieuboudreau** [comment]
I think it needs to be a different command (e.g. axondeepseg_patch), because the CLI `axondeepseg` points specifically to `main` of segment.py, and the patching is dealt with in another file

**Comment by mathieuboudreau** [comment]
Some useful tips:

* Tests should be written for this CLI (see [here](https://github.com/neuropoly/axondeepseg/blob/2bee818b5be963b11f57733b110f1818daebf402/test/test_segment.py#L215-L235) for examples)
* There are unit tests for patch extraction (not CLI) [here](https://github.com/neuropoly/axondeepseg/blob/2bee818b5be963b11f57733b110f1818daebf402/test/test_segment.py#L215-L235).

**Comment by jcohenadad** [comment]
> I think it needs to be a different command (e.g.axondeepseg_patch), because the CLI axondeepseg points specifically to main of segment.py, and the patching is dealt with in another file

Agreed. But maybe for the futur we could consider having different actions (like when calling "git push, git merge, etc.)

**Comment by mathieuboudreau** [comment]
I agree – I'll actually open an issue for that now, and if that one gets resolved sooner than this one, then we should go with your original proposal.

**Comment by mathieuboudreau** [comment]
Stale / no longer needed atm
