### ISSUE TITLE
Consolidate all CLI commands into a single entrypoint

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#146]
Currently, each CLI command have separate names (e.g. `axondeepseg` for segmentation, `axondeepseg_test` for integration).

As proposed by @jcohenadad in #145, we should refacture these into a single common entrypoint (e.g. `axondeepseg segment`, `axondeepseg test`, `axondeepseg patch`, etc.).

**Comment by vs74** [comment]
I want to know since `AxonDeepSeg patch` is having usage in `test/data_managment/test_dataset_building.py`, should I implement `axondeepseg_patch` in `AxonDeepSeg/data_managment/dataset_building`,  if not, then where should it be implemented?

**Comment by mathieuboudreau** [comment]
Stale
