### ISSUE TITLE
Unclear management of pixel size during training

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#152]
When training a new model (e.g., see [training_guideline.ipynb](https://github.com/neuropoly/axondeepseg/blob/master/notebooks/training_guideline.ipynb)), the dimension of the working pixel size is never explicit. This poses a problem when doing inference using this model, because it is not clear what resolution the input image will be resampled to (it should be resampled to the resolution of the trained model, but what is it??).

**Comment by mathieuboudreau** [comment]
Here's where they are currently set. Values are in micrometers I believe. 

https://github.com/neuropoly/axondeepseg/blob/9e59f536da6c709d0341999ae2b11945de588cb2/AxonDeepSeg/segment.py#L221-L237

As I mentionned in #141, currently all SEM/TEM model details are sparsley hardcoded throughout the project, and should be refractored in a single file so that its easier to add new modalities, and so that they are easier to locate.

**Comment by mathieuboudreau** [comment]
And I agree that the notebooks should be more verbose about these details.

**Comment by jcohenadad** [comment]
Thank you @mathieuboudreau!  Indeed, the modality-based resolution is highly problematic for 2 reasons: (i) the modality (SEM/TEM) is really not a good surrogate for resolution and (ii), the resolution of input images is completely ignored (e.g., training with images from different resolutions will induce size heterogeneity). One possible workaround is to refactor the code, asking to input image native resolution for ALL images in the training/validation sets.

For now, I'll fix the doc in the notebooks (PR #150).

**Comment by mathieuboudreau** [comment]
Yeah, point ii) is worrysome. I'm guessing that these sizes were simply picked because they allowed the wanted patch sizes for each modality.

**Comment by mariehbourget** [comment]
We can close this issue following ivadomed implementation.

> When training a new model (e.g., see [training_guideline.ipynb](https://github.com/neuropoly/axondeepseg/blob/master/notebooks/training_guideline.ipynb)), the dimension of the working pixel size is never explicit. This poses a problem when doing inference using this model, because it is not clear what resolution the input image will be resampled to

This is now solved with ivadomed as the pixel size is available in the "Resample" key of the tranformations parameter in the config file: https://ivadomed.org/configuration_file.html#resample. There are no hard-coded values anymore.

> Thank you @mathieuboudreau! Indeed, the modality-based resolution is highly problematic for 2 reasons: (i) the modality (SEM/TEM) is really not a good surrogate for resolution and (ii), the resolution of input images is completely ignored (e.g., training with images from different resolutions will induce size heterogeneity). One possible workaround is to refactor the code, asking to input image native resolution for ALL images in the training/validation sets.

There is currently another issue (#670) for a multi-resolution resolution pipeline that address this point in more details.
