### ISSUE TITLE
Refactor/revert functionality for data augmentation order

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#155]
This will (should) be addressed when refactoring ADS with higher level libraries like Keras/Pytorch (#141).

See discussion near the end of PR #150 for details of old/vs new functionality, and why we want to revert to the old method (or a "better" one that doesn't use values the key names are variables).

i.e. Something like this happened for all data augmentation key-val definitions in the config:

`da-flipping: {'activate': True, 'order': 2}` was redefined "recently" (months to a year ago) to `da-2-flipping-activate: True`

and the preferred way would be to revert back to something closer to the old way.

**Comment by mariehbourget** [comment]
Closing this issue as training and data augmentation are now done on ivadomed's side.
