### ISSUE TITLE
Pixel resampling for patching: general_pixel_size can not equal image's pixel_size_in_micrometer parameter

### ISSUE THREAD

**Issue by MelanieLu** [axondeepseg/axondeepseg#157]
When testing the function `dataset_building.raw_img_to_patches() ` to create new patches the error:
```
ValueError: 
Error: patch size must be smaller than dimensions of image.
```
raises if the value of the `general_pixel_size` input parameter the function is equal or larger than the actual pixel_size of the image, provided in `pixel_size_in_micrometer.txt` file associated with the image. 

This test was done by executing the first cells of `guide_dataset_building.ipynb `notebook

**Comment by mathieuboudreau** [comment]
Whats the command that you run, as well as the size of your image and input resolution you provide?

**Comment by mathieuboudreau** [comment]
Also, which image did you try (folder & file location on NeuroPoly server)

**Comment by mathieuboudreau** [comment]
Just did - thanks!

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
