### ISSUE TITLE
Refactor `data_management/dataset_bulding.py` for cleaner code

### ISSUE THREAD

**Issue by maf88** [axondeepseg/axondeepseg#194]
[`dataset_bulding.py`](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/data_management/dataset_building.py) has a lot of code that is similar through the different function. It woud be nice to see if some refactoring and OO programming can be done. I'm thinking about making a class/interface and then different instantiations depending on the usage we want.

**Comment by mariehbourget** [comment]
Closing as `data_management/dataset_bulding.py` does not exist anymore with the ivaodomed integration.
