### ISSUE TITLE
[Good Habit]: make a docstring for each modules

### ISSUE THREAD

**Issue by antmoev** [axondeepseg/axondeepseg#195]
At the beginning of the file, a module should have a meaningful documentation to present the intent of the module, even if it's small. 
Have a look on how powerful docstring can be:
- https://stackoverflow.com/a/2557196/1076483
PEP-257 on docstrings convention:
- https://www.python.org/dev/peps/pep-0257/

**Comment by mathieuboudreau** [comment]
Stale / we've adoped the practice
