### ISSUE TITLE
Refactor `compute_morphometrics`

### ISSUE THREAD

**Issue by antmoev** [axondeepseg/axondeepseg#198]
Some code is legacy, some comments are outdated, some code can be concatenated. This is one of the module that we use the most. Therefore it can be a good idea to refactor it! Some UT might need to be updated or even added!

**Comment by maf88** [comment]
Make sure we use `pathlib`and `logging` ;-)

**Comment by mathieuboudreau** [comment]
I'm not sure if this type of refactoring (i.e. refafactoring for the sake of refactoring) is a big priority at the moment (besides maybe adding logging). @jcohenadad thoughts?

**Comment by jcohenadad** [comment]
Agreed. Not a priority. Besides, logger should be deployed everywhere (not only in compute-morphonetrics)

**Comment by mathieuboudreau** [comment]
Stale
