### ISSUE TITLE
FSLeyes: integrate (?) into native ADS installation

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#205]
As of https://github.com/neuropoly/axondeepseg/pull/182, fsleyes can be installed manually. It would be nice to have it installed during ADS installation. 

TODO:
- Add fsleyes in `requirements.txt`
  - Test if ADS install works + usage in Windows, OSX and Linux

**Comment by mathieuboudreau** [comment]
Closing, this was resolved with our move to a conda installation.
