### ISSUE TITLE
Roadmap for converting to PyTorch

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#206]
This issue is mostly asking for a comprehensive roadmap for ensuring proper conversion of ADS to PyTorch. Things to consider:
- Testing
- Creating/Loading models (link with API)
- Notebooks
- Data augmentation (replace with existing modules, etc.)
- Possibility for weight transfer from existing models (e.g. ImageNet)
- Use of [MONAI](https://github.com/Project-MONAI/MONAI)

**Comment by mathieuboudreau** [comment]
Closing, this was done in IVADOMED.
