### ISSUE TITLE
Add blurring in data augmentation

### ISSUE THREAD

**Issue by tanguyduval** [axondeepseg/axondeepseg#21]
Some regions suffer from bad focus which bias the results: much fewer small axons detected.
Would be nice to detect that.

Bad Focus:
![image](https://user-images.githubusercontent.com/7785316/29142663-9b8e14ae-7d20-11e7-964f-ac32c7a8bdd1.png)

On Focus:
![image](https://user-images.githubusercontent.com/7785316/29142707-c26fbe88-7d20-11e7-9f2f-65d0f35c7548.png)

**Comment by mathieuboudreau** [comment]
Was done in #288
