### ISSUE TITLE
Implement new method to separate myelins

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#211]
Instead of the watershed which is fairly unstable and inaccurate, we could think of other (or complimentary) ways to separate myelin sheaths that touch. Similarly to what has been implemented in [AxonSeg](https://github.com/neuropoly/axonseg), we could take the center of mass of each axon, reconstruct the profile along the radial line, and spot the distance of the interface between the background and the outer myelin, and compute a robust median distance. Then, replace the outliers (i.e. those who are between two myelin touching) with the median value. See image below:

![IMG_1729](https://user-images.githubusercontent.com/2482071/56678135-fa777500-668f-11e9-83ad-566205766457.jpg)

**Comment by jcohenadad** [comment]
Approach implemented by @Stoyan-I-A works fairly well:

![image](https://user-images.githubusercontent.com/2482071/102104071-c1a78900-3dfb-11eb-8992-9c0aaec45abd.png)

However, it might be tricky in cases where there is a lot of packed axones.

**Comment by mathieuboudreau** [comment]
Was done in #108
