### ISSUE TITLE
Better Image Stitching Algorithm to reduce/handle error in patch overlap

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#218]
**Problem.**
Image Stitching used in AxonDeepSeg commonly encounters with distorted/occluded image at the boundary of overlapping patches. Neighboring blocks constrained by overlap used in AxonDeepSeg is outdated and results in poor stitching of patches. A lot of new stitching algorithms in the literature aims at reducing/minimizing the error due to stitching. 

**Proposed Solution**
1. One way to deal with this problem is using the minimum error boundary cut instead of neighboring blocks. http://vision.gel.ulaval.ca/~jflalonde/cours/4105/h14/tps/results/project/minghou/index.html
<img width="544" alt="Screenshot 2019-06-05 at 9 06 15 AM" src="https://user-images.githubusercontent.com/31419210/58958563-30207b00-8771-11e9-92c7-a7c68149a063.png">

2. We can also look at OpenCV stitching algorithms  SURF, SIFT (claims to be having good stitching ability for microscopy). https://www.pyimagesearch.com/2018/12/17/image-stitching-with-opencv-and-python/

3. Some open-source contributions to also look at 

- https://github.com/MATony/ImageStitch -VFMS(claims to better than autosticher, imageJ and photoshop)

**Comment by jcohenadad** [comment]
Related to https://github.com/neuropoly/axondeepseg/issues/74

**Comment by mariehbourget** [comment]
Another method we could use is averaging the prediction values in the overlap region. Part of the overlap at the outer edge of the overlap could be cropped as it is now and the inner part of the overlap averaged with the adjacent patches. We should implement it in collaboration with ivadomed where the averaging method is already implemented.

**Comment by mathieuboudreau** [comment]
Stale / no longer used
