### ISSUE TITLE
[Project] Correct statistics

### ISSUE THREAD

**Issue by tanguyduval** [axondeepseg/axondeepseg#22]
Assuming constant functions:  
- Sensibility = f(diameter)
- Specificity = f(diameter)
(e.g. Sensibility is worse on small axons)

Correct the Mean axon diameter.

**Comment by jcohenadad** [comment]
was the link to correction script added? was the info on README added? if (and only if) so reference it to the commit and close the issue.

**Comment by mathieuboudreau** [comment]
Stale / I think was specific to the paper / Harris is no longer here, too late to ask for scripts
