### ISSUE TITLE
Resolve warning due to scikit-image package.

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#239]
Currently the scikit-image package generates **32 warnings** mostly due to it's depreciation. Most of these warning are related to common problem `XY_TO_RC_DEPRECATION_MESSAGE` and    `Anti-aliasing will be enabled by default in skimage 0.15 to `. Screenshot below shows up the warnings 
<img width="1128" alt="Screenshot 2019-07-31 at 12 35 55 AM" src="https://user-images.githubusercontent.com/31419210/62184520-7d156d80-b32c-11e9-8995-02c65b33335e.png">

For more details refer to Travis build log

**Comment by vs74** [comment]
@mathieuboudreau, could you look into this issue ?

**Comment by mathieuboudreau** [comment]
Closing because there is no warning anymore since we moved to sci-kit 0.18.3
