### ISSUE TITLE
ERROR: tensorflow 1.9.0 has requirement setuptools<=39.1.0, but you'll have setuptools 41.0.1

### ISSUE THREAD

**Issue by amartinwong** [axondeepseg/axondeepseg#258]
I apologize because this probably has an easy fix, but I am not overly familiar with Python and could not find it described in the other issues. 

**Describe the bug**
I'm in the process of install axondeepseg
ERROR: tensorflow 1.9.0 has requirement setuptools<=39.1.0, but you'll have setuptools 41.0.1 which is incompatible

**To Reproduce**
1. Installed miniconda today on my 2018 MacBook Pro (OSX 10.14.6) and ads_venv
2. Downloaded AxonDeepSeg from website (not Git) 
Ran the install, appeared to be doing fine until this: 

Successfully built prettytable tabulate mpld3 networkx absl-py termcolor gast
**ERROR: tensorflow 1.9.0 has requirement setuptools<=39.1.0, but you'll have setuptools 41.0.1 which is incompatible.**
Installing collected packages: prettytable, numpy, tabulate, tqdm, pillow, scipy, raven, six, python-dateutil, pytz, pandas, scikit-learn, mpld3, pyparsing, cycler, kiwisolver, matplotlib, PyWavelets, decorator, networkx, scikit-image, pluggy, py, more-itertools, attrs, pytest, absl-py, astor, grpcio, werkzeug, markdown, protobuf, tensorboard, termcolor, gast, tensorflow, imageio, coverage, pytest-cov, axondeepseg
Successfully installed PyWavelets-1.0.3 absl-py-0.8.0 astor-0.8.0 attrs-19.1.0 axondeepseg-2.1 coverage-4.5.4 cycler-0.10.0 decorator-4.4.0 gast-0.3.2 grpcio-1.23.0 imageio-2.3.0 kiwisolver-1.1.0 markdown-3.1.1 matplotlib-2.2.2 more-itertools-7.2.0 mpld3-0.3 networkx-2.3 numpy-1.14.5 pandas-0.23.3 pillow-5.2.0 pluggy-0.6.0 prettytable-0.7.2 protobuf-3.9.1 py-1.8.0 pyparsing-2.4.2 pytest-3.5.0 pytest-cov-2.5.1 python-dateutil-2.8.0 pytz-2019.2 raven-6.8.0 scikit-image-0.13.1 scikit-learn-0.19.2 scipy-1.1.0 six-1.12.0 tabulate-0.8.2 tensorboard-1.9.0 tensorflow-1.9.0 termcolor-1.1.0 tqdm-4.24.0 werkzeug-0.15.6
(ads_venv) Frank-2:AxonDeepSeg Frank$ axondeep_test
-bash: axondeep_test: command not found

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6

Thank you in advance!

**Comment by mathieuboudreau** [comment]
@amartinwong Sounds like the `[setuptools](https://pypi.org/project/setuptools/)` package that you have installed by default in your virtual environment is outdated. Could you try running `pip install --upgrade setuptools` then try the AxonDeepSeg installation again?

**Comment by amartinwong** [comment]
Thank you for your quick reply! It seems that the `setuptools` package miniconda installed is too new (it's version 41.2.0) and the error message is saying that the tensorflow will only work with 39.1.0 or below. When I tried running `pip install --upgrade setuptools` it reinstalled 41.2.0.

**Comment by mathieuboudreau** [comment]
Oh sorry, I saw the version symbol wrong. You could try `pip install setuptools==39.1.0` instead.

**Comment by amartinwong** [comment]
Thank you, that worked!

**Comment by mathieuboudreau** [comment]
Great! Thanks for letting us know about this - I'll update the requiremznts file so that it downloads the needed version of that package

**Comment by amartinwong** [comment]
Thank you again, I sent you an email about this as it is somewhat off topic for this issues, but am hoping to use the program to analyze axons in light micrographs.

**Comment by mathieuboudreau** [comment]
Cool!

Another thing - are you sure you activated your conda environment? And that you have the most up-to-date AxonDeepSeg version downloaded? I'm asking because our installation requirements file (https://github.com/neuropoly/axondeepseg/blob/master/requirements.txt) should be trying to install tensorflow 1.13.1, not 1.9.0 as you say in your post title. So either you're trying to install axondeepseg in an environment that already has tensforflow 1.9.0 installed, or you have an older version of axondeepseg downloaded.

**Comment by amartinwong** [comment]
I checked and my AxonDeepSeg version is 2.2, my conda environment did need updating, from  `conda-package-han~        1.3.11-py37_0 --> 1.5.0-py37h1de35cc_0` Though before I updated it, when I ran `AxonDeepSeg_test` it passed, post-updating it continued to pass.

**Comment by mathieuboudreau** [comment]
Ok, no worries! Just wanted to check =)

**Comment by mathieuboudreau** [comment]
Closed, tensorflow is not used since our move to ivadomed
