### ISSUE TITLE
Introduce pixel size to show correct distance in FSLeyes

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#262]
By default, FSLeyes assigns 1 vox = 1 mm, yielding wrong distance when looking at an image through FSLeyes, as shown below:
![Screen Shot 2019-09-24 at 12 11 04 PM](https://user-images.githubusercontent.com/2482071/65529698-a124a380-dec4-11e9-8e91-1bd5427b4c43.png)

It would be nice take pixel size into consideration when displaying the voxel-to-absolute coordinate relationship.

**Comment by mathieuboudreau** [comment]
Stale - no longer using FSLeyes
