### ISSUE TITLE
Out segmentation looks pixelated at border, beyond native resolution

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#264]
When applying ADS model on an image with better resolution than the model used, the output segmentation looks "pixelated", as shown below:

![Screen Shot 2019-10-01 at 12 33 53 PM](https://user-images.githubusercontent.com/2482071/65981873-012cc400-e448-11e9-809c-9c84a55a0e5a.png)

This is caused by the resampling from the lower res patch to the native resolution. A way to mitigate this effect would be to apply a smoothing filter to the output segmentation, making sure it does not affect the border definition (i.e., morphometrics should not change).

**Comment by mathieuboudreau** [comment]
Stale / we're using different models now
