### ISSUE TITLE
Improve axon filling method

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#268]
Various improvements include:
- Move the algorithm of [on_fill_axons_button](https://github.com/neuropoly/axondeepseg/blob/master/ads_plugin.py#L490) outside of the file `ads_plugin.py` to ADS new library: `postprocessing.py`.
- the method [get_myelin_centroids](https://github.com/neuropoly/axondeepseg/blob/master/ads_plugin.py#L540) should be renamed `get_axon_centroids` (as well as the input variable name)
- provide a means to identify outliers (e.g. open myelin, or artifactual myelin dots)
  - example of rule: if axon area is superior than myelin area, this axon/myelin has a problem.
  - the culprits would be identified by a new mask (e.g. green color) that would be easily recognized on FSLeyes

**Comment by mathieuboudreau** [comment]
Stale - no longer using FSLeyes
