### ISSUE TITLE
Add a scaling parameter instead of using native resolution for prediction

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#269]
Sometimes, specifying a resolution which is different from the native acquisition resolution produces better prediction. The current problem is that when computing morphometrics, the specified resolution is used, causing morphometrics results to be wrong.

To overcome this issue, we should add a "scaling" parameter, that would fictively change the native resolution of the image, independently from the morphometrics calculations.

**Comment by mathieuboudreau** [comment]
Stale, no longer in use
