### ISSUE TITLE
Look at preprocessing methods for improving segmentation results

### ISSUE THREAD

**Issue by maxwab** [axondeepseg/axondeepseg#28]
Preprocessing is applied per image right now. For each patch that enters the network:
* We equalize the histogram of the patch.
* We normalize the patch.

This may not be optimal. Moreover, since we apply preprocessing per patch, we do not carry prior information from the training set to the test image, like we usually we do when we normalize using the mean and variance from the training set.

It would be useful:
* To further investigate the effect and necessity of histogram equalization.
* To find motivation to apply per-image preprocessing in the litterature.
* To try a more conventional way of doing normalization.
_Notes_
Tests of different preprocessing/normalisation techniques are now possible by just creating a new function in patch_management_tools.py and using this function instead of apply_legacy_preprocessing as we do right now.

**Comment by jcohenadad** [comment]
maybe use [CLAHE](https://imagej.net/Enhance_Local_Contrast_(CLAHE))

**Comment by mathieuboudreau** [comment]
Stale / no longer done in this repo
