### ISSUE TITLE
Better exception management for the software

### ISSUE THREAD

**Issue by maxwab** [axondeepseg/axondeepseg#29]
The software lacks some exception management right now.

The idea is to manage failures to find a file, a model ... And to notify the user of the exact error.

Ideally the user should never encounter a Python error when launching the software axondeepseg.

**Comment by mathieuboudreau** [comment]
Related to issue #76 (Implement more complete testing module), the exception handling should be tested for as well.

**Comment by mathieuboudreau** [comment]
* [ ] Add exception handling for case in issue #29

**Comment by mathieuboudreau** [comment]
Stale / been done piecewise over the years, it's much better than when this issue was opened
