### ISSUE TITLE
Develop script to make sure one image is not included in training data

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#300]
### context
It is possible that a training data contain duplicates (e.g. human error related to gathering of data, naming the same image differently). 

### possible solution
create a function that would loop across all images and perform a paired-comparison (e.g. metric: mutual information, cross-correlation, etc.) to identify duplicates and remove them.

note: this could already exist: before coding, look for existing code.

once created this function could go under the `split_data()` function.

**Comment by mathieuboudreau** [comment]
Stale / training no longer done in this repo
