### ISSUE TITLE
SEM vs TEM network architecture

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#308]
In the paper, SEM network had 3 convolutions per layer and TEM had 2, whereas in the current [default models on OSF](https://osf.io/bj9eu/), there are 2 convolutions per layer in the config_network files for both SEM and TEM.

Is it normal or is it a bug?
Should we train SEM with 2 or 3 convolutions per layer?

For reference, previous "v1" models in [split_data branch](https://github.com/neuropoly/axondeepseg/tree/split_data/AxonDeepSeg/models) (merged on 2020-03-03) had 3 convolutions for SEM and 2 for TEM.

**Comment by mariehbourget** [comment]
It is not possible to train on bireli's GPU with the original SEM architecture with 3 convolutions per layer and a batch size of 8, but it can be run with a batch size of 7.
Comparative results will follow as soon as possible.

**Comment by jcohenadad** [comment]
> It is not possible to train on bireli's GPU with the original SEM architecture with 3 convolutions per layer and a batch size of 8, but it can be run with a batch size of 7.

@mariehbourget can you please elaborate what it is "not possible"? please detail with specific constraints, etc. so we can possibly work this out

**Comment by mathieuboudreau** [comment]
@mariehbourget can this be closed now? What decision was made in the IVADOMED model?
