### ISSUE TITLE
Implement optional destination folder in download_models CLI

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#323]
As discussed in PR #322, the download_model() function now accept destination folder in arguments. We should implement that feature for the CLI tools as well.

**Comment by vs74** [comment]
@mathieuboudreau would you like to work on this issue or I could take it up?

**Comment by mathieuboudreau** [comment]
@vs74 feel free to do it if you want. Otherwise I can.

**Comment by mathieuboudreau** [comment]
Done in #387
