### ISSUE TITLE
Training with soft labels

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#326]
We are currently training our models with binarized labels.
This occurs in 3 steps, in order:
1) Resampling to target resolution in [raw_images_to_patches](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/data_management/dataset_building.py#L58) in `dataset_building.py` with `order=0` (nearest neighbor). This function writes new 512x512 files on disks when building the dataset and cannot easily be swaped with step 2 at the moment.
2) Mask binarization in [descritize_mask](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/data_management/input_data.py#L124)  in `input_data.py` where we create the tensor sent to the training with 3 channels of 0's and 1's.
3) Data augmentation in [train_network.py](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/train_network.py#L140) : all data augmentation are in nearest neighbor interpolation except blurring.

We want to try training with "soft labels" i.e. without binarization.

I'm currently testing this in` mhb/soft-labels` branch. Here are the changes I've made for each steps:
1) I switched from order 0 (nearest) to order 1 (linear) interpolation in [dataset building](https://github.com/neuropoly/axondeepseg/blob/bfa81cb415338517abea0cbabcb0b91a197faab2/AxonDeepSeg/data_management/dataset_building.py#L58), `order=1` (linear) is the default.
2) I removed the binarization of the mask and replaced it [here](https://github.com/neuropoly/axondeepseg/blob/bfa81cb415338517abea0cbabcb0b91a197faab2/AxonDeepSeg/data_management/input_data.py#L147) with 2 scales from 0 to 1 for background VS myelin and for myelin VS axon. (This is a test for now, the implementation is for three classes only and could be improved to generalize for n classes.)
3) I switched from nearest to linear interpolation in [data augmentation](https://github.com/neuropoly/axondeepseg/blob/bfa81cb415338517abea0cbabcb0b91a197faab2/AxonDeepSeg/train_network.py#L140).

Regarding blurring:

- We usually don't use blurring for our training, we had a project to removed it entirely from the codebase specifically to avoid soft labels in [issue #288 ](https://github.com/neuropoly/axondeepseg/issues/288).
- The blurring in Albumentation is done by default with a random-sized kernel from 3 to 7.
- Since blurring happens after binarization, the labels would be soft anyway in that case.

Data augmentation options:
- The options available in the code are: Flip, Shift, Elastic Transform, Rotate and Blur.
- For our default models on OSF, only Flip, Shift and Elastic Transform were used, so I'm using only those 3 for the tests. (I  could redo an entire test with all options to).

Some issues along the way:
- Correct me if I'm wrong, I think that in data augmentation, both the mask and the images are currently resampled using nearest neighbor interpolation. It seems weird to me that we are doing nearest neighbor on the image.
- The function [labellize_mask_2d](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/data_management/input_data.py#L102) which is supposed to returns the mask in [0-1] domain is not doing anything since it returns the same patch as the one passed in argument. The function is used in descritize_mask [here](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/data_management/input_data.py#L131) before binarization. In fact, the threshold (0 to 1) are convert to (0 to 255) [here](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/data_management/input_data.py#L137) because the mask variable after calling labellize_mask_2d contains values from 0 to 255 (and not 0 to 1). The function is also called in step 1 when [building dataset](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/data_management/dataset_building.py#L61).  Correct me if I'm wrong, but I think we sould remove the function as it is very confusing when reading the code.
- "Rescaling" in data augmentation is not defined but there is a variable for it in the [code](https://github.com/neuropoly/axondeepseg/blob/85686c983399a07f26b1dc10aea2b006ce867cec/AxonDeepSeg/train_network.py#L88), the config files ("da-1-rescaling-activate") and in the 02-training_guidelines jupyter notebook.
- The blurring option ("da-5-gaussian_blur-activate") doesn't appear in the notebook.

**Comment by jcohenadad** [comment]
> Correct me if I'm wrong, I think that in data augmentation, both the mask and the images are currently resampled using nearest neighbor interpolation. It seems weird to me that we are doing nearest neighbor on the image.

indeed, i would do linear on the image (and possibly also on the segmentation, but that's more an exploratory question). but: if that requires complex refactoring, i would leave it as it is for now (waiting for ivadomed integration, which will solve that problem).

> The function labellize_mask_2d which is supposed to returns the mask in [0-1] domain is not doing anything since it returns the same patch as the one passed in argument. The function is used in descritize_mask here before binarization. In fact, the threshold (0 to 1) are convert to (0 to 255) here because the mask variable after calling labellize_mask_2d contains values from 0 to 255 (and not 0 to 1). The function is also called in step 1 when building dataset. Correct me if I'm wrong, but I think we sould remove the function as it is very confusing when reading the code.

seems weird-- could you open an issue specific to that problem?

> "Rescaling" in data augmentation is not defined but there is a variable for it in the code, the config files ("da-1-rescaling-activate") and in the 02-training_guidelines jupyter notebook.

assuming "rescaling" means "affine" (choice of word is bad-- i would use affine), then maybe it is included in elastic transfo. If not, we should use it. But as said above, if too complex, wait for ivadomed.

> The blurring option ("da-5-gaussian_blur-activate") doesn't appear in the notebook.

to remove everywhere

**Comment by mariehbourget** [comment]
Update:
With the ivadomed implementation, we can now easily do the training with soft labels (i.e. no binarization after data augmentation) with the `soft_gt` parameter and SoftSeg pipeline documented here: https://ivadomed.org/configuration_file.html#soft-gt

**Comment by mathieuboudreau** [comment]
As mentionned, this feature was implemented in ivadomed, closing
