### ISSUE TITLE
Upgrade ADS requirements to be compatible with ivadomed

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#327]
In order to run axondeepseg and ivadomed in the same environment, we would need to upgrade the following requirements:

`pillow==6.2.0` to at least `==7.0.0`
`scikit-learn==0.19.2` to at least `==0.20.3`
`tqdm== 4.24.0` to at least `==4.30`
`numpy==1.16.4` to at least `==1.16.6`

ADS tests won’t pass with `pillow==7.0.0`.
<details>
  <summary>Details:</summary>
  
```
test/test_integrity_test.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
AxonDeepSeg/integrity_test.py:40: in integrity_test
    prediction = axon_segmentation([path_testing], ["image.png"], path_model, config_network, prediction_proba_activate=True, verbosity_level=4)
AxonDeepSeg/apply_model.py:258: in axon_segmentation
    gpu_per=gpu_per, verbosity_level=verbosity_level)
AxonDeepSeg/apply_model.py:51: in apply_convnet
    path_acquisitions, acquisitions_resolutions, resampled_resolutions, verbose_mode=verbosity_level)
AxonDeepSeg/apply_model.py:326: in load_acquisitions
    original_acquisitions.append(ads.imread(path_img))
AxonDeepSeg/ads_utils.py:261: in imread
    raw_img = imageio.imread(filename)
../miniconda/envs/ads_ivado_a/lib/python3.7/site-packages/imageio/core/functions.py:206: in imread
    reader = read(uri, format, 'i', **kwargs)
../miniconda/envs/ads_ivado_a/lib/python3.7/site-packages/imageio/core/functions.py:123: in get_reader
    format = formats.search_read_format(request)
../miniconda/envs/ads_ivado_a/lib/python3.7/site-packages/imageio/core/format.py:673: in search_read_format
    if format.can_read(request):
../miniconda/envs/ads_ivado_a/lib/python3.7/site-packages/imageio/core/format.py:188: in can_read
    return self._can_read(request)
../miniconda/envs/ads_ivado_a/lib/python3.7/site-packages/imageio/plugins/pillow.py:97: in _can_read
    Image = self._init_pillow()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Format PNG-PIL - Portable network graphics>

    def _init_pillow(self):
        with self._lock:
            if not self._pillow_imported:
                self._pillow_imported = True  # more like tried to import
                import PIL
                if not hasattr(PIL, 'PILLOW_VERSION'):  # pragma: no cover
>                   raise ImportError('Imageio Pillow requires '
                                      'Pillow, not PIL!')
E                   ImportError: Imageio Pillow requires Pillow, not PIL!

../miniconda/envs/ads_ivado_a/lib/python3.7/site-packages/imageio/plugins/pillow.py:81: ImportError
```
</details>

But all tests passed with the latest version of `pillow==7.2.0` and the versions mentioned above for the three other libraries.

**Comment by mariehbourget** [comment]
Update: I tried to install ivadomed in the same conda environment as ADS in python 3.7.
I have not tested any of this. This is just a breakdown of the differences in requirements.

For compatibility, these upgrades are still needed in ADS for:
`pillow==6.2.0` to at least `==7.2.0`
`scikit-learn==0.19.2` to at least `==0.20.3`
`tqdm== 4.24.0` to at least `==4.30`

In addition:
`matplotlib==3.1.0` to at least `==3.3.0`

Other libraries that are installed with ivadomed (but not in requirements):
`numpy=1.19.1`, ADS requires `==1.16.4` (numpy >=1.7 from h5py->ivadomed==2.1.0)
`requests=2.24.0`, ADS requires `==2.20.1`
`scipy=1.5.2`, ADS requires `==1.3.0` (scipy>=0.19.1 from scikit-learn>=0.20.3->ivadomed==2.1.0)

For tensorboard, I had the following message when installing ivadomed:
`Requirement already satisfied: tensorboard in /home/mhbourget/miniconda/envs/ads_ivado_37a/lib/python3.7/site-packages (from ivadomed==2.1.0) (1.13.1)`
but that error while trying to execute training in ivadomed:
`ImportError: TensorBoard logging requires TensorBoard version 1.15 or above`

Finally, ivadomed is supported in python 3.6, 3.7 and 3.8, whereas ADS is only supported in python 3.7.

**Comment by jcohenadad** [comment]
to not have to maintain the versions in both ivadomed and ADS, i suggest we remove the version requirement on ADS for packages that are already present in ivadomed, and install ivadomed _before_ these packages (so that the versions required by ivadomed will be specified). @kousu @joshuacwnewton is that a good strategy?

**Comment by joshuacwnewton** [comment]
> to not have to maintain the versions in both ivadomed and ADS, i suggest we remove the version requirement on ADS for packages that are already present in ivadomed

### Short answer

I very much agree with loosening `install_requires` within `setup.py` for ADS. But, I'm not sure I agree with the suggestion to stop maintaining requirements entirely. I think it's worthwhile to still try to specifiy the minimal requirements, just like [IVADOMED does](https://github.com/ivadomed/ivadomed/blob/master/requirements.txt). 

> and install ivadomed before these packages (so that the versions required by ivadomed will be specified).

If both ADS and IVADOMED have compatible minimal requirements (which I think is likely -- the range of acceptable versions can be quite large, see IVADOMED), then in theory they should be able to be installed together without needing to specify an order.

### Longer answer

Both projects are currently parsing `requirements.txt` directly for `install_requires` inside `setup.py`. 

https://github.com/neuropoly/axondeepseg/blob/b0c06509a6dd612837830c36a0e04f0f3aff22ae/setup.py#L17-L20

https://github.com/neuropoly/axondeepseg/blob/b0c06509a6dd612837830c36a0e04f0f3aff22ae/setup.py#L50

But, `requirements.txt` and `setup.py` are meant to have very different purposes. Here's a very useful [StackOverflow answer](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py) that explains why.

> * `setup.py` should declare the loosest possible dependency versions that are still workable. Its job is to say what a particular package can work with.
> * `requirements.txt` is a deployment manifest that defines an entire installation job, and shouldn't be thought of as tied to any one package. Its job is to declare an exhaustive list of all the necessary packages to make a deployment work.
> * Because these two things have such different content and reasons for existing, it's not feasible to simply copy one into the other.

I'm guessing that ADS used `pip freeze > requirements.txt` at some point. But, by bringing these strict requirements over to `setup.py`, I believe conflicts were practically inevitable (hence #327).

So, my longer-term suggestion would be to use @mariehbourget's findings for minimum version requirements directly in `setup.py`, and stop using `requirements.txt` for the pip install.

**Comment by mathieuboudreau** [comment]
Closed, they work well together now.
