### ISSUE TITLE
FSLeyes: apply model with different resolutions than default SEM and TEM

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#334]
When applying model in FSLeyes, the resolution is set by default to 0.1 [here](https://github.com/neuropoly/axondeepseg/blob/3bcc87d29816d881dcc4b0eda5f075cdcb564544/ads_plugin.py#L284), and then change to 0.01 [here](https://github.com/neuropoly/axondeepseg/blob/3bcc87d29816d881dcc4b0eda5f075cdcb564544/ads_plugin.py#L323) if a "TEM" model is selected.

It would be nice to be able to choose a resolution when applying the model.
(e.g. If a user trains his own model with a general_pixel_size different than 0.1 or 0.01, and wants to use FSLeyes to make manual corrections or compute morphometrics.)

**Comment by Stoyan-I-A** [comment]
What would be the best way to implement this in the interface? One option would be to add a text line where the resolution could be modified by the user.

**Comment by mariehbourget** [comment]
Yeah, that would work. Or maybe it could be a text box like the one for "Enter pixel size in micrometer"?
In any case, I think it should be mandatory only if the user choose something else than the default models.

**Comment by mathieuboudreau** [comment]
>It would be nice to be able to choose a resolution when applying the model.
(e.g. If a user trains his own model with a general_pixel_size different than 0.1 or 0.01, and wants to use FSLeyes to make manual corrections or compute morphometrics.)

If a user trains a model with a different general_pixel_size, and wants to use FSleyes, we should simply add that model as another drop-down option. I think adding the option to the user of setting the general_pixel_size might actually make them mistakenly input the image pixel size, and not the pixel size that was used for training (which they might not even know).

**Comment by mathieuboudreau** [comment]
Either that, or even better this value should actually be saved in the model file, and be read from it. (since the value will always be tied with the model)

**Comment by mariehbourget** [comment]
Right now, if a model is in `AxonDeepSeg/models`, it appears in the drop down menu and can be used in FSLeyes. The problem is that the general_pixel_size is hardcoded in the plugin and cannot be changed (either 0.1, or 0.01 if "TEM" is in the name of the model).
I agree that it would be a good idea to save this value in the training config.
We will have to document this very well because the general_pixel_size is set in the dataset_building notebook (where we do patches) and not in the training notebook.

**Comment by mariehbourget** [comment]
@Stoyan-I-A 
As mentioned in #428, in version 4, the model resolution is extracted by ivadomed from the config file in the model folder. This means that we will no longer need this option in FSLeyes. I checked brieftly and I think we forgot to remove some harcoded values in the ADS plugin that are no longer used.
Ex: [here](https://github.com/axondeepseg/axondeepseg/blob/6d745492cc091576922b579bc67c56a72905b838/ads_plugin.py#L384) and [here](https://github.com/axondeepseg/axondeepseg/blob/6d745492cc091576922b579bc67c56a72905b838/ads_plugin.py#L425)

**Comment by Stoyan-I-A** [comment]
> I think we forgot to remove some harcoded values in the ADS plugin that are no longer used.

You're right, they can be removed from the plugin file. I'll do that soon.

**Comment by mariehbourget** [comment]
I'm closing this issue because with version 4.0, the model resolution is no longer hardcoded but extracted directly from the json model config file by ivadomed. Unused variables related to this have been removed from the plugin in #611.
