### ISSUE TITLE
Create ADS forum to centralize users questions

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#337]
When members of the core developer team receive an email from a user about issues with ADS (install, feature, etc.), we should redirect to a user forum. The earlier we set up a forum, the better it is.

Suggestions:
- standalone forum a la SCT (http://forum.spinalcordmri.org/c/sct)
- new section under neurostar (https://neurostars.org/)

**Comment by jcohenadad** [comment]
after looking at where to host our ADS forum on neurostar i realized that it might be confusing for users to find ADS-specific forum. Neurostar is *huge*, has a lot of categories, etc. so people not familiar with it might get confused.

any feedback welcome before we take any decision

**Comment by alexfoias** [comment]
If we chose to deploy our own forum, we might be able to install the forum on the same server as [sct forum](http://forum.spinalcordmri.org/c/sct). Here is some [unofficial documentation](https://linuxhandbook.com/multiple-discourse-install/).

**Comment by mathieuboudreau** [comment]
Closed; we're using GitHub Discussions now.
