### ISSUE TITLE
Update Contribution guidelines

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#359]
We have contributing guidelines in 3 different places:

- [CONTRIBUTING.rst](https://github.com/neuropoly/axondeepseg/blob/master/CONTRIBUTING.rst)
- [Wiki: Guidelines for contribution](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution)
- [Wiki: Rules for commits and issues labelling (git)](https://github.com/neuropoly/axondeepseg/wiki/Rules-for-commits-and-issues-labelling-(git))

Joshua is working on harmonizing the contributing guidelines across NeuroPoly projects with the new [NeuroPoly Contributing Guidelines](https://www.neuro.polymtl.ca/open_source/contributing) on wiki.

Those guidelines are compatible with current ADS guidelines except:

- Versioning: ADS versioning differs from MAJOR.MINOR.PATCH
- Maybe Versioning should be specific to each software and indicated in each project wiki.

Here are the changes that I proposed in ADS:

1. Remove [CONTRIBUTING.rst](https://github.com/neuropoly/axondeepseg/blob/master/CONTRIBUTING.rst):
- The content is almost identical to NeuroPoly Contributing Guidelines
- There are some ADS specific information that could be moved to the ADS wiki:
-- Issue Body: testing data (not up-to-date)
-- Issue Labels
-- Issue Examples
-- Some specific information concerning documentation and tests

2. Remove [Wiki:Guidelines for contribution](https://github.com/neuropoly/axondeepseg/wiki/Guidelines-for-contribution):
- Bug reporting template is not useful (there is already a template when opening an issue)
- The rest is very similar to NeuroPoly Contributing Guidelines
- Make sure that theses 2 points are in the NeuroPoly guidelines:
-- Cite any papers, packages or code snippets used to implement the feature.
-- Each pull request should propose ONLY ONE feature (independent from other features in the code).

3. Modify [Wiki: Rules for commits and issues labelling (git)](https://github.com/neuropoly/axondeepseg/wiki/Rules-for-commits-and-issues-labelling-(git)):
- The commit message part is not used (do we really want that?)
- The labelling part for issues and PR should be kept (like [SCT](https://github.com/neuropoly/spinalcordtoolbox/wiki/Contributing%3A-Labelling-issues-and-pull-requests)) and the link add to it in the NeuroPoly Contributing Guidelines.
- Everything else is very similar to NeuroPoly Contributing Guidelines
- Changes made in [SCT labels](https://github.com/neuropoly/spinalcordtoolbox/issues/2915) that would make sense in ADS:
-- Change the `refactoring` label to a PR "category" label (instead of "context") to distinguish code structure changes from `enhancement` changes
-- Change description of `enhancement`
-- Add description for `refactoring`
-- Change `testing` label to context instead of category
-- Other category labels to add? 	`documentation-internal`, `CI`, `git/github`

4. Rename [Wiki: How to create a new release](https://github.com/neuropoly/axondeepseg/wiki/How-to-create-a-new-release) to `Versioning` an add the link in the NeuroPoly Contributing Guidelines

**Comment by jcohenadad** [comment]
tagging @joshuanewton here

**Comment by jcohenadad** [comment]
> Versioning: ADS versioning differs from MAJOR.MINOR.PATCH

we go with MAJOR.MINOR.PATCH

> Remove CONTRIBUTING.rst:

OK for remove

> Remove Wiki:Guidelines for contribution:

OK for remove

> Modify Wiki: Rules for commits and issues labelling (git):

We can do exactly as done in https://github.com/neuropoly/spinalcordtoolbox/wiki/Contributing%3A-Labelling-issues-and-pull-requests, and update https://www.neuro.polymtl.ca/open_source/contributing#pr_labels

**Comment by mariehbourget** [comment]
> Rename [Wiki: How to create a new release](https://github.com/neuropoly/axondeepseg/wiki/How-to-create-a-new-release) to `Versioning` an add the link in the NeuroPoly Contributing Guidelines

We'll keep the name (How to create a new release), the link has been added to Versioning in Neuropoly wiki.

**Comment by joshuacwnewton** [comment]
Thank you for the tag @jcohenadad, and thank you for taking the time to create this issue with an in-depth write-up @mariehbourget. :slightly_smiling_face: 

> - Make sure that theses 2 points are in the NeuroPoly guidelines:
>   -- Cite any papers, packages or code snippets used to implement the feature.
>   -- Each pull request should propose ONLY ONE feature (independent from other features in the code).

Thanks much for this suggestion. I very much agree with adding the first point.

For the second point, how do you feel about this wording? "Each pull request should try to address only one issue, with each issue representing a single feature or bug report."

> The labelling part for issues and PR should be kept (like SCT) and the link add to it in the NeuroPoly Contributing Guidelines.

If each of the projects ends up with a similar scheme for labels (e.g. context, category), perhaps this information could be put directly into NeuroPoly Contributing Guidelines, and we wouldn't even need individual pages on each GitHub Wiki.

> We'll keep the name (How to create a new release), the link has been added to Versioning in Neuropoly wiki (https://www.neuro.polymtl.ca/open_source/contributing#versioning)

I agree with this, too. 

In fact, I'm wondering if the NeuroPoly Contributing Guidelines should even have "Versioning". It doesn't necessarily seem like information that new contributors need to know about to be able to contribute. (It more seems like information needed by each of the specific, dedicated project maintainers who are responsible for creating releases -- that's why I like your suggestion of keeping the "How to create a new release" page on the developer Wiki.)

**Comment by mathieuboudreau** [comment]
Stale

**Comment by joshuacwnewton** [comment]
(minor minor nitpick, but for stale issues, I think it might be beneficial to close as "not planned" rather than "completed")

**Comment by mathieuboudreau** [comment]
I didnt see those options - i didnt even know they existed!! Thanks!
