### ISSUE TITLE
Reassess patch overlap default value

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#385]
The default value for patch overlap in inference is 25 pixels.

Segmentation tests of optical microscopy images with the default TEM model showed a strong patch pattern in segmentation, particularly on region with lower contrast.

Increasing the overlap to 50 pixels greatly improve the results with less noise and no (or few) patch pattern.
Further increase to 75 pixels didn't change the result significantly and takes more time to process (more patches).

We may want to reassess the default overlap value for inference to improve stitching and segmentation.
Related issue #218

**Comment by mariehbourget** [comment]
Update on this issue regarding the ivadomed implementation:

In ivadomed (and ADS v4.0.0), the predictions in the overlap region are averaged.
Previously in ADS v3.3.0, the predictions in the overlap region were cropped.
What it means is that for the same patch size, an overlap of 25 in ADSv3 is equivalent to an overlap of 50 in ivadomed (ADSv4).

The current default we set in ADSv4 with ivadomed models is 48.

**Comment by mathieuboudreau** [comment]
Stale - no longer in use
