### ISSUE TITLE
CLI to check versions of installed packages

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#391]
Following this [comment](https://github.com/neuropoly/axondeepseg/issues/390#issuecomment-725662499).

We want to implement a CLI to check dependencies versions, similar to [SCT's `sct_check_dependencies`](https://github.com/shimming-toolbox/shimming-toolbox/issues/161#issuecomment-725028653).

**Comment by mathieuboudreau** [comment]
Stale
