### ISSUE TITLE
Use squeletonization to close myelin

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#400]
As pointed out in #397, there is a need to manually correct myelin masks, including closing them so that the flood fill algo works. There might be ways to "close" myelin masks automatically after a [squeletonization](https://scikit-image.org/docs/dev/auto_examples/edges/plot_skeleton.html) algo. To investigate...

**Comment by Stoyan-I-A** [comment]
For some visualization:
![image](https://user-images.githubusercontent.com/43790661/99916353-d2228300-2cd7-11eb-979d-eda3ee9f8a90.png)

**Comment by mathieuboudreau** [comment]
@hermancollin this old issue may be relevant to the user issue you were discussing today.

**Comment by mathieuboudreau** [comment]
Stale
