### ISSUE TITLE
Update ADS to be compatible with python 3.8

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#403]
ADS is currently supported only with python 3.7.
We would like ADS to be compatible with python 3.8 as well in preparation for the integration with ivadomed (which supports 3.6, 3.7 and 3.8).

**Comment by mathieuboudreau** [comment]
Do we also need to make it 3.6-compatible?

**Comment by mariehbourget** [comment]
> Do we also need to make it 3.6-compatible?

I don't think so, my idea was more to "move forward" in parallel with ivadomed.

On a side note, we originally removed support of 3.6 because of FSLeyes, but FSLeyes now support 3.6 as well, so ADS would probably be ok to (see comments [here](https://github.com/neuropoly/axondeepseg/issues/303#issuecomment-649728747))

**Comment by mathieuboudreau** [comment]
As discussed in #405, we're goign to pause this issue and resume when making the move to IVADOMED.

**Comment by mathieuboudreau** [comment]
Closed because we made this change with version 4.0's move to IVADOMED.
