### ISSUE TITLE
Implement transfer learning

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#410]
For an application on nerve segmentation, there is a working branch that implements transfer learning: https://github.com/neuropoly/axondeepseg/tree/vs/transfer-nerve-seg

This branch is deemed to disappear at some point once ivadomed becomes a dependency of ADS.

**Comment by mariehbourget** [comment]
Closing this issue as the ivadomed integration is done.
Transfer learning is implemented in ivadomed as documented here: https://ivadomed.org/configuration_file.html#transfer-learning
