### ISSUE TITLE
CLI fails after FSLeyes install

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#411]
When installing ADS alone, everything is working fine.
When installing both ADS and FSLeyes, `CLI` and `axondeepseg_test` are no longer working (Ubuntu 20.04 in WSL1).

<details>
  <summary>Error message</summary>
  
```
Traceback (most recent call last):
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 8.0.1 (/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages), Requirement.parse('pillow==6.2.0'), {'AxonDeepSeg'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/bin/axondeepseg_test", line 33, in <module>
    sys.exit(load_entry_point('AxonDeepSeg', 'console_scripts', 'axondeepseg_test')())
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/bin/axondeepseg_test", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 93, in load
    module = import_module(match.group('module'))
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mhbourget/axondeepseg/AxonDeepSeg/integrity_test.py", line 9, in <module>
    from AxonDeepSeg.testing.segmentation_scoring import *
  File "/home/mhbourget/axondeepseg/AxonDeepSeg/testing/segmentation_scoring.py", line 18, in <module>
    import AxonDeepSeg.ads_utils
  File "/home/mhbourget/axondeepseg/AxonDeepSeg/ads_utils.py", line 18, in <module>
    import imageio
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/imageio/__init__.py", line 22, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/imageio/core/__init__.py", line 10, in <module>
    from .util import Image, Dict, asarray, image_as_uint, urlopen
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/imageio/core/util.py", line 20, in <module>
    import pkg_resources
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/mhbourget/miniconda/envs/ads_venv_test_fsl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel>=0.26' distribution was not found and is required by tensorflow
```
</details>

This seems related to #393 and #395, with a discrepancy of the Pillow package.

I tried re-installing ADS after FSLeyes, it fixes the problem for CLI and axondeepseg_test, also FSLeyes is working as expected.
Here is the packages that were re-insatlled:
<details>
  <summary>Re-installed packages</summary>
  
```
Installing collected packages: numpy, scipy, pillow, matplotlib, urllib3, idna, requests, AxonDeepSeg
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.4
    Uninstalling numpy-1.19.4:
      Successfully uninstalled numpy-1.19.4
  Attempting uninstall: scipy
    Found existing installation: scipy 1.5.3
    Uninstalling scipy-1.5.3:
      Successfully uninstalled scipy-1.5.3
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.0.1
    Uninstalling Pillow-8.0.1:
      Successfully uninstalled Pillow-8.0.1
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.3.3
    Uninstalling matplotlib-3.3.3:
      Successfully uninstalled matplotlib-3.3.3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.11
    Uninstalling urllib3-1.25.11:
      Successfully uninstalled urllib3-1.25.11
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Attempting uninstall: requests
    Found existing installation: requests 2.25.0
    Uninstalling requests-2.25.0:
      Successfully uninstalled requests-2.25.0
  Attempting uninstall: AxonDeepSeg
    Found existing installation: AxonDeepSeg 3.2.0
    Uninstalling AxonDeepSeg-3.2.0:
      Successfully uninstalled AxonDeepSeg-3.2.0
  Running setup.py develop for AxonDeepSeg
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fslpy 3.4.0 requires dataclasses, which is not installed.
Successfully installed AxonDeepSeg idna-2.7 matplotlib-3.1.0 numpy-1.16.4 pillow-6.2.0 requests-2.20.1 scipy-1.3.0 urllib3-1.24.3
```
</details>

We were planning in #395 to update the documentation to mention to re-install FSLeyes after ADS. I think it would be better to always re-install ADS after FSLeyes. That way, we would have the same versions installed whether FSLeyes is installed or not (which is not the case right now).

**Comment by mathieuboudreau** [comment]
Thanks for looking into this @mariehbourget.

The more I think about it, the less I like the idea of the strategy to tell users to reinstall either ADS or FSLeyes just in order to override some of the package rules. The package rules are there for a reason, and if we need to reinstall ADS just to override the versions install by FSLeyes (which overrode the original ADS ones), then maybe something bigger is the problem. By re-installing ADS to force versions, we risk installing versions of packages that are incompatible with FSLeyes, which we won't detect in our tests.

What we can control though is our own package rules, and I think these problems we've been having with FSLeyes may be an indication that they are too strict. It may be worth exploring some `>=` rules instead of the strictest `==` rules for the packages that are overriden by FSLeyes. This means that we'd be installing the latest versions and FSLeyes shouldn't override them anymore, and we'd actually be testing the ADS software for these versions. The disadvantage of this is that we won't have a git record of the versions actually being used at different points in time like we do now, however we would be able to find this with a little bit of research which is just a mild inconvenience. This is what most other softwares do anyways (`>=` rules), so we're still using good practices regardless.

@jcohenadad thoughts?

**Comment by mathieuboudreau** [comment]
p.s. we could easily find the rules that need to be changed by doing a `diff` between the `pip freeze` before and after installing FSLeyes, and changing the rules that are in our requirements files that are different between these two.

**Comment by jcohenadad** [comment]
My first question would be: Does this bug appear in the CI? If not, can add a test to make sure that our master (and release) versions don't carry this bug? 

Regarding the avoidance of the `==` rule: I agree. In fact for SCT, ivadomed and shimming-toolbox projects we are now adopting the `~=` convention, so maybe we could go with it for ADS as well?

As for the checking what exact version of libraries were used retroactively, as mentioned by @mathieuboudreau we can do a pip freeze and save that pip freeze for every release, e.g. [as done in SCT](https://github.com/neuropoly/spinalcordtoolbox/blob/release/requirements-freeze.txt).

@kousu @joshuacwnewton do you have any recommendations?

**Comment by joshuacwnewton** [comment]
I agree about moving away from `==` for requirements.txt, and only using `pip freeze` for releases. 

But, just to clarify this one comment:

> Regarding the avoidance of the `==` rule: I agree. In fact for SCT, ivadomed and shimming-toolbox projects we are now adopting the `~=` convention, so maybe we could go with it for ADS as well?

Our use of `~=` was only for `h5py`, because we had a very clear idea of which versions were safe to use and which weren't. We knew that `2.10.0` was safe, and we knew that `3.0.0` and above broke things, so saying `h5py~=2.10.0` was a way of saying "We want 2.10.0 at the very minimum, or any security patches that arrive after." 

More generally, however, you can and should be [much more flexible in your `install_requires` specification](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires) by using `<`, `>`, `<=`, `>=` and etc. It all depends on your understanding of the upper and lower bounds of the requirements. (In fact, it's possible we could have been even more flexible for `h5py` too, even, by saying something like `h5py<3.0` instead of `h5py~=2.10.0`.)

**Comment by jcohenadad** [comment]
thank you for your insights @joshuacwnewton

**Comment by ahill187** [comment]
Not sure if this is related, or maybe I installed it wrong, but when I followed the instructions here: https://axondeepseg.readthedocs.io/en/latest/documentation.html#installation, I got to the section [Graphical User Interface](https://axondeepseg.readthedocs.io/en/latest/documentation.html#graphical-user-interface-gui-optional), and was fine up until the line:
```
fsleyes
```
That gave me this error:
```
ImportError: ('Unable to load OpenGL library', 'dlopen(OpenGL, 10): image not found', 'OpenGL', None)
```

I followed the order of the instructions, so installed the `axondeepseg` package from `GitHub`, and then installed `fsleyes`.

#### OS & Python Version
```
Python 3.7.9
MacOSX Big Sur
```

**Comment by mathieuboudreau** [comment]
Thank you for your detailed issue report @ahill187 !

When MacOSX Big Sur got released, we found out that the default FSLeyes installation is incompatible by default with this OS, and the FSLeyes developers have not expressed a desire to fix it anytime soon. However someone in the community has found a quick fix that you can do yourself by editing a specific file, which I tried and worked for me! https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=FSL;8ee55ea9.2011

I'd say give that a shot! If you have questions, let us know.

@mariehbourget maybe we should add a warning and the link above in the installation doc re: Big Sur & FSLeyes?

**Comment by ahill187** [comment]
> Thank you for your detailed issue report @ahill187 !
> 
> When MacOSX Big Sur got released, we found out that the default FSLeyes installation is incompatible by default with this OS, and the FSLeyes developers have not expressed a desire to fix it anytime soon. However someone in the community has found a quick fix that you can do yourself by editing a specific file, which I tried and worked for me! https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=FSL;8ee55ea9.2011
> 
> I'd say give that a shot! If you have questions, let us know.
> 
> @mariehbourget maybe we should add a warning and the link above in the installation doc re: Big Sur & FSLeyes?

@mathieuboudreau that makes sense, thank you! Yah I think a warning note in the documentation and maybe a link to the fix could be a good idea?

**Comment by jcohenadad** [comment]
things i tried on macOs catalina:
- virtualenv & pip install fsleyes --> ✅ 
however, what might not work according to @Stoyan-I-A is conda venv and pip install fsleyes:
- todo: try that

suggestion: include fsleyes in requirements.

**Comment by mathieuboudreau** [comment]
Closing because this was resolved when we moved to a conda env install with FSLeyes installed automatically.
