### ISSUE TITLE
Create unit test data of dummy axons

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#422]
Currently, images of synthetic axons are [generated by hand on a software like paint, and then put on OSF.](https://github.com/neuropoly/axondeepseg/pull/399#discussion_r541314003) We shoudl avoid that. Instead, we should have python code that generates those dummy that so that:
- we can parametrize it
- we don,t need to manually put them on a repos

To do this, we can start from PR #179.

**Comment by vs74** [comment]
Shall we first deal with PR #399 (implement ellipse minor axis) or first towards PR #179 which add tests for generating synthethic images of axons for the testing purpose?

**Comment by mathieuboudreau** [comment]
I'm going to quickly revisit #179 right now to see if it can be quickly improved to 1) include ellipses, and 2) be prepared to be merged.

**Comment by mathieuboudreau** [comment]
This was completed in #179
