### ISSUE TITLE
Limit file size on commit

### ISSUE THREAD

**Issue by alexfoias** [axondeepseg/axondeepseg#423]
Problem: we would like to forbid commits that include files bigger than XX MB.
Possible implementations: 

- https://stackoverflow.com/questions/39576257/how-to-limit-file-size-on-commit/39578014#39578014
- https://gist.github.com/kiwidamien/a6a909ee196be8795b30431079074d64

Crossref: https://github.com/neuropoly/spinalcordtoolbox/issues/3100 https://github.com/shimming-toolbox/shimming-toolbox/issues/199 https://github.com/ivadomed/ivadomed/issues/583

**Comment by kousu** [comment]
https://github.com/neuropoly/spinalcordtoolbox/issues/2705

**Comment by vs74** [comment]
I will look into this issue.

**Comment by jcohenadad** [comment]
also see here: https://github.com/ivadomed/ivadomed/pull/682

**Comment by mathieuboudreau** [comment]
Stale, see https://github.com/axondeepseg/axondeepseg/pull/464
