### ISSUE TITLE
Experiment with Shape-Aware weight maps, Multilevel Watershed and Feature Pyramind Networks

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#431]
**PAPER : -** 
[Transfer Learning Framework for cell segmentation with incorporation of geometric features .pdf](https://github.com/neuropoly/axondeepseg/files/5724866/Transfer.Learning.Framework.for.cell.segmentation.with.incorporation.of.geometric.features.pdf)

There are three key insights from this paper we would like to test and if results are satisfactory, then we wish to integrate into ADS.

1. **Shape-Aware Weight Maps** - The idea is to incorporate geometric properties of the axon-myelin while training our network to have better prediction of instances of axon/myelin at the borders or when these instances are adjacent and clustered, improve automatic morphometrics computation by ADS and finally resolve the class imbalance problem. For more details about it refer to section `2.2 Preprocessing and Shape-Aware weight maps` of this paper.

2. **Multi level Watershed Post Processing** - Key idea is to resolve touching myelin issue ( see issues - #211, #24). For more information regarding the algorithm, see the section `2.3 Multi-level Watershed Post-processing of the paper`.

3. **Feature Pyramid Networks (FPN)** - Currently, ADS uses [Unet ( AutoEncoder) ](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/network_construction.py)architecture. We wish to look at whether are there any performance gains if we use Feature Pyramid Networks (FPN) over Unet architecture. One key difference between UNET and FPN is that UNET only make final predictions at the last layer, while FPN uses all the resolutions in its expansion phase which contribute to the output predictions, which could improve our predictions.

**Comment by vs74** [comment]
Can anyone label this issue as **good internship project** ? Thanks in advance

**Comment by mathieuboudreau** [comment]
Stale
