### ISSUE TITLE
Documentation: Add instructions regarding the usage of ADS CLI's 

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#435]
Currently, the documentations only lists out detailed instructions on how to use `axondeepseg` and `axondeepseg_test` CLI. 

The documentation seems to be lacking the instructions about the remaining CLI's that we do use in the project :- 

1. `download_models`
2. `download_tests`

It would be nice to have information about the remaining ADS CLI's  in the [RTD](https://axondeepseg.readthedocs.io/en/latest/documentation.html#) for the developers, contributors or even users. 

**PS:** Perhaps we could touch on this issue after ivadomed integration

**Comment by mathieuboudreau** [comment]
download_tests shouldn't really have a public API, as it's only intended to be called during installation. We could clarify that.

**Comment by vs74** [comment]
> download_tests shouldn't really have a public API documentation, as it's only intended to be called during installation. We could clarify that internally for developers.

yeah, I agree that `download_tests` CLI doesn't need to added in RTD. For this CLI, we could add instructions on [WIKI ](https://github.com/neuropoly/axondeepseg/wiki).

**Comment by mathieuboudreau** [comment]
Has been completed
