### ISSUE TITLE
Advertising ADS

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#437]
This issue lists ideas to advertise ADS in the future.
Suggestions are welcomed, feel free to edit and add to the list.

1. Organize Kaggle competition:
    - Features: myelin touching, accommodate various modalities
    - $5k prize

2. Very Active reddit communities:
    - [r/deeplearning](https://www.reddit.com/r/deeplearning/)
     - [r/MachineLearning](https://www.reddit.com/r/MachineLearning/)

**Comment by jcohenadad** [comment]
Tagging @nekohayo so he is aware

**Comment by mathieuboudreau** [comment]
Stale
