### ISSUE TITLE
FSLeyes - Add option to choose filenames (prefix and/or suffix) of manually saved masks 

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#445]
I'm using the. plugin, and in my workflow I'd like to load masks generated by ADS in a previous session and edit the masks for some minor correction. When I'm done, I'd like to be able to specify the prefix and/or suffix, so that I can do something like save the masks with the same prefix as before but add the suffix (_corrected), so that I have a record of both the original masks and the new edited masks in a consistently named list.

Also, by default, the merged masks saved by this method saved them as "ADS_seg.png", "ADS_seg-myelin.png", and "ADS_seg-axon.png", which is problematic for a lot of reasons: 1- it doesn't follow our convention since the merged masks file doesn't have a suffic (is this handled by @vs74 new PR?), and 2- it makes it impossible to save multiple masks in the same folder (I have multiple images per folder)

**Comment by vs74** [comment]
My PR #441 handles the naming convention for FSLeyes with an agreed-upon naming convention as discussed in issue #439. But it doesn't cater to the scenarios when a user wishes different suffix/prefix for the segmentations. Perhaps once we merge PR #441, we can deal with this behavior as well.  

To your second point regarding multiple masks, I agree with you that with the current implementation we are unable to save multiple masks ( of different images). I was going to tag @Stoyan-I-A  for this in my PR #441 for the same reason, but thanks for bringing this issue out. To resolve this there would be a slight modification needed in the [on_save_segmentation_button](https://github.com/neuropoly/axondeepseg/blob/5af8cbb1e782092ac46e0586eca0f827c0eff938/ads_plugin.py#L374) function. I could make changes in my PR #441 or we can handle it in separate PR.

**Comment by Stoyan-I-A** [comment]
> To resolve this there would be a slight modification needed in the [on_save_segmentation_button](https://github.com/neuropoly/axondeepseg/blob/5af8cbb1e782092ac46e0586eca0f827c0eff938/ads_plugin.py#L374) function. I could make changes in my PR #441 or we can handle it in separate PR.

You could implement it if you want. How should it work though? We could make it so every mask that is set visible is saved, but I feel like it wouldn't be intuitive for the user to set every mask visible on the FSLeyes canvas.

**Comment by vs74** [comment]
Yes @Stoyan-I-A, I was thinking about saving for every visible mask on the FSLeyes canvas. But you have a good point regarding keeping all the masks visible and saving them would feel odd. For now, let's keep the PR #441 for only fixing the naming convention.

**Comment by mathieuboudreau** [comment]
Stale - no longer using FSLeyes
