### ISSUE TITLE
Documentation: Discussion about references for AxonDeepSeg

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#454]
As of now, the current [references](https://github.com/neuropoly/axondeepseg#references) section (**README.md**) is not updated/maintained. Although there are a lot more citiations for ADS, the [**README.md** ](https://github.com/neuropoly/axondeepseg#references)file only lists a fraction of them.

Do we plan to update the **README.md** for the references and if yes how frequently?

Also, do we wish to list out all the references in the **README.md**? In my opinion if we go by this approach, then at some point it will make the **README.md** much verbose. Instead we can update the references in[ RTD](https://github.com/neuropoly/axondeepseg) similar to what SCT does(see [here](https://spinalcordtoolbox.com/en/stable/overview/references.html))?

What are your thoughts on this?

**Comment by mathieuboudreau** [comment]
Stale
