### ISSUE TITLE
Centralize hardcoded variables  in `config.py` script

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#463]
There are some locations in the codebase such as look at [here ](https://github.com/vs74/axondeepseg/blob/c7b0aee2bc45a700963fc08a0f806931e56deec4/AxonDeepSeg/segment.py#L27) where hardcoded variables are used. Instead, we should centralize all the hardcoded variables in the [config.py](https://github.com/neuropoly/axondeepseg/blob/master/config.py) script.

**Comment by mathieuboudreau** [comment]
Stale
