### ISSUE TITLE
Add FSLeyes doc for new settings menu

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#473]
Currently, the only user doc we have for the ADS plugin in FSLeyes is for manual correction and the video tutorial on RTD.

When the new settings menu is completed, we should add some doc about:
- Settings for segmentation (overlap, zoom factor, pixel size)
- Settings for morphometrics (axon shape, pixel size)

and/or update the video tutorial.

**Comment by Stoyan-I-A** [comment]
I started writing some documentation for the plugin. You can find it here: https://docs.google.com/document/d/1jnFeaoZ5Nzs35heutzk00pdjMeNK61ljG_PeYrvoMsw/edit#heading=h.jpdmwtqrvl4x

I'm not sure if we want to keep it in a Google Doc or add a page to our ReadTheDocs.

**Comment by jcohenadad** [comment]
> I started writing some documentation for the plugin. You can find it here: https://docs.google.com/document/d/1jnFeaoZ5Nzs35heutzk00pdjMeNK61ljG_PeYrvoMsw/edit#heading=h.jpdmwtqrvl4x
> 
> I'm not sure if we want to keep it in a Google Doc or add a page to our ReadTheDocs.

amazing ❤️ . I would definitely put it in RTD

**Comment by Stoyan-I-A** [comment]
Not directly related to the settings menu, but I made a video tutorial on how to perform a typical segmentation workflow using the plugin.
https://drive.google.com/file/d/1FlAX24_PHes4ikRu-1yYT4sJtmvbHRqt/view?usp=sharing

If you watch the video too soon after I upload it, it will have a low resolution. Just give it some time to be processed in the Google Drive.

**Comment by jcohenadad** [comment]
> Not directly related to the settings menu, but I made a video tutorial on how to perform a typical segmentation workflow using the plugin.
> https://drive.google.com/file/d/1FlAX24_PHes4ikRu-1yYT4sJtmvbHRqt/view?usp=sharing
> 
> If you watch the video too soon after I upload it, it will have a low resolution. Just give it some time to be processed in the Google Drive.

This is fantastic @Stoyan-I-A ! Thank you so much

**Comment by hermancollin** [comment]
Update: yesterday I bought a used iMac so I'll definitely be able to help with this in the following weeks. I would start with what @Stoyan-I-A drafted and then create a new section in the RTD.

**Comment by Stoyan-I-A** [comment]
In our last meeting, it was suggested to open an issue to create a new video for the installation and another issue to update the video links in the documentation page. However I feel like we could address that in this issue since it's already about updating the documentation. We would just need to edit the title.

Anyway, I made the new video explaining how to install ADS: https://drive.google.com/file/d/1XKEUBTjZchttxqIyY3NWmQoYHiddyRcz/view?usp=sharing

**Comment by mathieuboudreau** [comment]
Stale - no longer using FSLeyes
