### ISSUE TITLE
Logo incompatible with dark browser settings

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#480]
See below:

<img width="894" alt="Capture d’écran 2021-03-22 à 10 28 31" src="https://user-images.githubusercontent.com/1421029/111993314-6cb19800-8af9-11eb-92c5-47150fd3df9c.png">

**Comment by jcohenadad** [comment]
ah! who would have thought when we were designing this logo 🤣

**Comment by dyt811** [comment]
See issue being addressed at https://github.com/ivadomed/ivadomed/issues/731. TLDR need to fix at 3rd repo by updating the PNG with white background... or patch every where this image is used via some fancy dark/light mode detection script. I think former is easier.

**Comment by mathieuboudreau** [comment]
This is an issue now for #682 because it has dual light/dark themes.

I'll look into if there's documented design principles on how to best design logos for dual light/dark theme interfaces.

**Comment by mathieuboudreau** [comment]
So in terms of resolving this in Github, there's appears to be a way to change the image depending on if the user is using light or dark mode. Details here: https://dev.to/arnavkr/using-darklight-mode-specific-images-in-github-markdown-3iln

@Stoyan-I-A could you check to see if Napari has a similar "switching" feature (maybe the mode is kept in a variable?). If so, then the solution would just be to design "dark mode" logo/images, and then use these features.

**Comment by mathieuboudreau** [comment]
These resources have ideas on dark mode logo design:

https://www.emailonacid.com/blog/article/email-development/dark-mode-logo-problems/
https://www.actionrocket.co/email-design-review/how-to-create-a-dark-mode-friendly-email-logo
https://reaction.ca/blog/adapting-branding-for-dark-mode/

**Comment by Stoyan-I-A** [comment]
It is possible to find which theme the user has with these lines:

```
from napari.settings import get_settings
theme_id = get_settings().appearance.theme
print(theme_id)  # outputs 'dark'
```

From here, we could decide which image to load (or perhaps update the one that is currently loaded).

**Comment by hermancollin** [comment]
> <img alt="Capture d’écran 2021-03-22 à 10 28 31" width="894" src="https://user-images.githubusercontent.com/1421029/111993314-6cb19800-8af9-11eb-92c5-47150fd3df9c.png">

Strangely enough, with my github dark theme, the grey is more light so the logo still looks good:
 
![Screenshot_20230113_131746](https://user-images.githubusercontent.com/83031821/212391305-a9d42154-1176-4a15-ac60-10085b14a18e.png)

Wouldn't it be possible to simply tweak the current image of the logo? I feel like this would be way less complicated. We only need to add a white outline for the logo to pop

 
![logo_glow2](https://user-images.githubusercontent.com/83031821/212392611-a9003511-0e2a-41d6-9a9c-ce01e4d61b6c.png)

or

![logo_outline](https://user-images.githubusercontent.com/83031821/212394584-38677a4d-09fd-4edf-8531-2d5aa34d96bd.png)

This wouldn't change anything for the normal light theme.

**Comment by mathieuboudreau** [comment]
Ping - should revisit, see some discussions suggesting SVGs:

https://stackoverflow.com/questions/67187091/creating-svg-that-appears-black-in-light-mode-and-light-in-dark-mode
