### ISSUE TITLE
ADS installation error due to `conda-forge::pyopengl-3.1.5-py_0`

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#499]
## **Describe the bug**

To test Stoyan's PR #490 on a Linux machine with GPU access, I tried installing ADS on that machine. 

While doing so, I encountered an installation error.

Here is the error log, which occurs when I try to set up a virtual environment using this command `conda env create -f environment.yml -n ads_venv`

<summary>
<details>

```

(base) ➜  axondeepseg git:(master) conda env create -f environment.yml -n ads_venv
Collecting package metadata (repodata.json): | WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
\ WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
- WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: /
\ Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::pyopengl-3.1.5-py_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::pyopengl-3.1.5-py_0
location of failed script: /opt/conda/envs/ads_venv/bin/.pyopengl-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Warning: Missing OpenGL driver, install with yum install mesa-libGL-devel or equivalent

stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/ads_venv/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/opt/conda/envs/ads_venv/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/opt/conda/envs/ads_venv/lib/python3.7/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/opt/conda/envs/ads_venv/lib/python3.7/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
AttributeError: 'NoneType' object has no attribute 'glGetError'

return code: 1

()
```
</details>
</summary>

I tried doing a fresh install in a new virtual environment, but it didn't help. 

**NOTE :-** Our old installation seemed to work on the same Linux machine, but the new installation seems to have some issues.

## **Platform**
 - OS:  Ubuntu 18.04
 - AxonDeepSeg version number: git master
 - CUDA: 11.0
 - GPU: NVIDIA A100

**Comment by vs74** [comment]
Upon digging further, doing an install of libGL files via `apt-get install libgl1-mesa-glx` first solved the issue. I am wondering is it possible to resolve the issue through **conda** itself. Does anyone have any clues on this?

**Comment by vs74** [comment]
Since there could be a possibility we might update the installation instructions for ADS once ivadomed is integrated, this issue can be halted for now. 

This issue should be revisited again once the integration is complete.

**Comment by vs74** [comment]
Also, I would like to mention one point in regards to this issue that I didn't touch on that meeting; the installation that is failing now was working with our previous installation. So it's likely a **conda** issue and how ADS being installed rather than a system issue.

**Comment by mathieuboudreau** [comment]
Stale
