### ISSUE TITLE
Move/Copy data from OSF and package them with git versioning

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#506]
**Describe the problem**

Current issues with hosting data on OSF:
- OSF is cumbersome to use (too many clicks, specific APIs that the team needs to learn to use), 
- not compatible with git
- limited in size
- Datasets are spreadout across multiple OSF repos:
  - https://osf.io/yp4qg/
  - https://osf.io/bj9eu/
- Currently, [model packages](https://osf.io/sv7u2/) include testing data, which makes it difficult to update separately. Related to #508.

**Proposed solution**
Host all the datasets that are used for training models using git/git-annex technology. If data are private and/or too large for Github, they can be hosted on NeuroPoly's internal git server (data.neuro.polymtl.ca). If data are public and small size, they can go under example: **https://github.com/axondeepseg/data-testing**. 

Pros:
- Harmonization with current best practices in reproducible science;
- Harmonization with internal lab practice;
- Can accommodate private data;
- Can train using multiple BIDS datasets (e.g. ivadomed can take as input multiple BIDS datasets and aggregate them);
- We can easily encode in the ivadomed config file the git commit hashtag;

For inspiration: 
- https://github.com/spinalcordtoolbox/sct_testing_data
- https://github.com/ivadomed/data-testing

## Details of the strategy

- Move **test_segmentation.zip** to https://github.com/axondeepseg/data-example
- Move test files under: https://github.com/axondeepseg/data-testing
- Move models under: https://github.com/axondeepseg/XXX, with XXX being the name of the model. Create one repo per model.
Wait to move the raw/ data. They will ultimately be moved to our internal server with git-annex.

**Comment by vs74** [comment]
> For inspiration: https://github.com/sct-data/

Is the repo a private one as I can't access it? It displays **404 error.**

**Comment by jcohenadad** [comment]
> > For inspiration: https://github.com/sct-data/
> 
> Is the repo a private one as I can't access it? It displays **404 error.**

sorry @vasudev-sharma, the link has changed, it is now: https://github.com/spinalcordtoolbox/sct_testing_data
( I also updated the link in my original message: https://github.com/neuropoly/axondeepseg/issues/506#issue-858986482)

**Comment by hermancollin** [comment]
Update:
- [x] Move test_segmentation.zip to https://github.com/axondeepseg/data-example
- [x] Move test files under: https://github.com/axondeepseg/data-testing
- [x] Move TEM model under: https://github.com/axondeepseg/default-TEM-model
- [x] Move SEM model under: https://github.com/axondeepseg/default-SEM-model
- [x] Move seg_pns_bf model under: https://github.com/axondeepseg/seg-pns-bf-model

questions: 
- I uploaded the uncompressed folders onto the repos. Should I replace them for the compressed version instead? Not sure if the original OSF links are hardcoded somewhere inside some ADS script. If this is the case, we should consider keeping them compressed to avoid breaking anything
- The models all natively contained a readme file with instructions on how to train the model. Should I cleanup these files and remove OSF mentions to avoid future confusion? 
- Minor: IIUC the seg_pns_bf model is the default OM one? Should we change the name of the repo to make it more explicit?

**Comment by mariehbourget** [comment]
> * Minor: IIUC the seg_pns_bf model is the default OM one? Should we change the name of the repo to make it more explicit?

I can answer this one:
`model_seg_pns_bf` is the new naming convention for models, shared with `ivadomed` (https://github.com/ivadomed/ivadomed/wiki/repositories), so eventually it's the default_SEM/TEM that will be renamed to match the convention (when we retrain them on ivadomed)

**Comment by jcohenadad** [comment]
> I uploaded the uncompressed folders onto the repos. Should I replace them for the compressed version instead? Not sure if the original OSF links are hardcoded somewhere inside some ADS script. If this is the case, we should consider keeping them compressed to avoid breaking anything

No, it is good to keep it uncompressed for human readability and also in case we only update one file. However, when creating a release, a .ZIP (and Tarball) file will automatically be created on Github, and we will point to that ZIP file for downloading from ADS.

> The models all natively contained a readme file with instructions on how to train the model. Should I cleanup these readme files and remove OSF mentions to avoid future confusion?

It is _very_ important to always have a README in a repository, that explains all the useful information that there is to know. Put yourself in the shoes of a new student finding this repository for the first time: what will you want to know?
- What is the purpose of this repository?
- How was the model trained? On what data? what version of the data? What code? What version of the code? What syntax for training? etc.

The same applies to data: where are the data coming from? etc.

So you can curate the README and ask us for feedback

**Comment by hermancollin** [comment]
Thanks @mariehbourget for the clarification. Very clear, as always.

> However, when creating a release, a .ZIP (and Tarball) file will automatically be created on Github, and we will point to that ZIP file for downloading from ADS.

So do you want me to create a release? Or should we wait after re-training via ivadomed?

> So you can curate the README and ask us for feedback

Updated the READMEs for the 3 models and deleted the old ones to avoid redundancy and put everything in one place. You can go take a look:
- [TEM](https://github.com/axondeepseg/default-TEM-model) ; 
- [SEM](https://github.com/axondeepseg/default-SEM-model) ; 
- [OM](https://github.com/axondeepseg/model-seg-pns-bf)

**Comment by jcohenadad** [comment]
> So do you want me to create a release?

yes

> Updated the READMEs for the 3 models and deleted the old ones to avoid redundancy and put everything in one place. You can go take a look

LGTM! Please open an issue in TEM and SEM repos to mention that repos name needs to be updated at some point (following the convention, and add link to convention)-- thanks!

**Comment by hermancollin** [comment]
Created releases for [data-example](https://github.com/ivadomed/data-testing/releases/tag/r20210322), [data-testing](https://github.com/axondeepseg/data-testing/releases/tag/r20210615), [OM model](https://github.com/axondeepseg/model-seg-pns-bf/releases/tag/r20210615), [TEM model](https://github.com/axondeepseg/default-TEM-model) and [SEM model](https://github.com/axondeepseg/default-SEM-model/releases/tag/r20210615)

I chose to use the following convention for releases tag: r+YEAR+MONTH+DAY, following the ivadomed naming convention for models, data, etc. Feel free to suggest a better alternative.

If everything is OK, I can post on slack to notify rest of ADS team.

**Comment by mariehbourget** [comment]
> Created releases for [data-example](https://github.com/ivadomed/data-testing/releases/tag/r20210322), [data-testing](https://github.com/axondeepseg/data-testing/releases/tag/r20210615), [OM model](https://github.com/axondeepseg/model-seg-pns-bf/releases/tag/r20210615), [TEM model](https://github.com/axondeepseg/default-TEM-model) and [SEM model](https://github.com/axondeepseg/default-SEM-model/releases/tag/r20210615)

Small thing: links for data-example is for ivadomed in your comment, can you update the link? thanks!

**Comment by hermancollin** [comment]
> Small thing: link for data-example is for ivadomed in your comment, can you update the link? thanks!

Bien vu. I updated the link. @mariehbourget, you're like this little guy from Kirikou. Nothing gets past you.
![kirikou_robot](https://user-images.githubusercontent.com/83031821/122110138-3334b400-cdec-11eb-9ce7-719b5ba9e271.jpeg)

Also (maybe it is too early for this) but I could open PRs to adapt the ADS code where all these repos were referenced from OSF.

**Comment by mariehbourget** [comment]
> Also, maybe it is too early for this, but I could open PRs to adapt the ADS code where all these repos were retrieved from OSF.

I think you can go ahead with the PRs for the update. Except for `data_example` that should be updated in @vasudev-sharma PR #518.
Thanks!

**Comment by mathieuboudreau** [comment]
Closing because this was completed.
