### ISSUE TITLE
Update categories

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#511]
Currently these are the [categories](https://github.com/neuropoly/axondeepseg/discussions/categories) we have:

![image](https://user-images.githubusercontent.com/2482071/115754901-b1d02080-a36a-11eb-8a54-2d1196da1a01.png)

I find that some of the categories are unnecessary and somewhat overlap with each other. 

I suggest we go for:
- 🙏  ‎  Help needed
  - Are you having trouble using ADS? Ask the community for help.
- 💡   ‎  Ideas of new features
  - Share ideas for new features.
- #️⃣  ‎   Bug reports, suggestions for code refactoring
  - If you encounter a bug, or if you would like to discuss technicalities, please post here.

**Comment by mathieuboudreau** [comment]
Updated. Also added:

🙌Show and tell
Show off something you've made or published with ADS
