### ISSUE TITLE
Tests: implement and validate ellipse inner and outer perimeters 

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#517]
The PR #501 implements the inner perimeter (axon perimeter) and outer perimeter(axonmyelin perimeter) of the myelin and validates it for a circle using a simulated image. However, in this recently merged PR, the ellipse perimeter was validated manually rather than using tests on the simulated image. 

We would certainly want to verify the inner and outer perimeter of the ellipse using the latest master branch (merged PR #501) with using mathematical formulas of the simulated ellipse.

**Comment by mathieuboudreau** [comment]
Stale
