### ISSUE TITLE
Remove `exit()` calls from the scripts

### ISSUE THREAD

**Issue by vasudev-sharma** [axondeepseg/axondeepseg#524]
When we wish to write a custom script to lets say perform either segmentation or morphometrics extraction as a subtask, the python process exits due to the `exit()` calls https://github.com/neuropoly/axondeepseg/blob/6cc6ade5f8aa594a66ddec556f08ab15501d12d3/AxonDeepSeg/morphometrics/launch_morphometrics_computation.py#L150 https://github.com/neuropoly/axondeepseg/blob/6cc6ade5f8aa594a66ddec556f08ab15501d12d3/AxonDeepSeg/morphometrics/launch_morphometrics_computation.py#L211
https://github.com/neuropoly/axondeepseg/blob/6cc6ade5f8aa594a66ddec556f08ab15501d12d3/AxonDeepSeg/segment.py#L363
https://github.com/neuropoly/axondeepseg/blob/6cc6ade5f8aa594a66ddec556f08ab15501d12d3/AxonDeepSeg/segment.py#L405

We probably don't want this behaviour as it terminates the custom script in the middle. This recently happened with me when I was working on morphometrics computation for Alan's data. 

I would instead prefer going for `try-catch-exception` block to prevent this behaviour. Any suggestions for alternative methods are welcome.

**Comment by mathieuboudreau** [comment]
Stale
