### ISSUE TITLE
Enriching the SEM dataset

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#545]
The ADS SEM dataset is fairly small and contains only "rat" data.

Several SEM images are available in `duke/histology/rat` (and maybe other species as well).
Other images are available in `duke/projects/axondeepseg/raw_data/data_SEM` in folders `done` and `to_correct` where "first" version of manual masks seem to already exist.

Related to this [issue](https://github.com/axondeepseg/data_axondeepseg_sem/issues/5) and [comment](https://github.com/axondeepseg/data_axondeepseg_sem/pull/4#discussion_r669106558).

**Comment by mathieuboudreau** [comment]
Stale, closing
