### ISSUE TITLE
morphometrics fail on images with alpha channel

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#552]
**Describe the bug**
Morphometrics computations fail when inputting some images, as discussed in #551. Even after converting the image to 8-bit grayscale, an alpha channel was still present (probably an undesired artifact produced when correcting the segmentations). 

**To Reproduce**

Launch morphometrics on these images taken from #551:
<details><summary>masks</summary>

![ID1_seg-myelin](https://user-images.githubusercontent.com/50454820/128307539-f7cebda7-234b-4a40-9fe0-4cd9900b96b5.png)
![ID1_seg-axon](https://user-images.githubusercontent.com/50454820/128307548-c7d07ab0-586c-41a7-9c2b-fc63ffcd88a2.png)
![ID1_seg-axonmyelin](https://user-images.githubusercontent.com/50454820/128307571-1e69fd69-cd0b-438b-81e5-46965bda8e47.png)
</details>

**Note**
`launch_morphometrics_computation` uses `matplotlib.imread()` to read the segmented images whereas `postprocessing:generate_and_save_colored_image_with_index_numbers()` uses `PIL.Image.open()`

AxonDeepSeg v3.2.0 (master)

**Comment by mariehbourget** [comment]
Elsewhere in the code, we use the function [imread](https://github.com/neuropoly/axondeepseg/blob/443c0579f417f8b1d0046e3904f9d54220b6091e/AxonDeepSeg/ads_utils.py#L254) from `ads_utils.py` to open RGB, RGBA or grayscale files directly in grayscale. We should probably do the same to correct the issue.

**Comment by mariehbourget** [comment]
Just a note, I ran into this issue again last week.
In #584, we updated all tests to use the `imread` function from `ads_utils.py` but there are still 2 instances of `matplotlib.imread()` in `launch_morphometrics_computation` that are causing errors when images have an alpha channel.

**Comment by mathieuboudreau** [comment]
Stale
