### ISSUE TITLE
Remove hardcoded filename in merge_masks()

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#554]
Just noticed this while working on #547 

https://github.com/neuropoly/axondeepseg/blob/443c0579f417f8b1d0046e3904f9d54220b6091e/AxonDeepSeg/visualization/merge_masks.py#L21

The output filename should not be hardcoded. I don't thinks it's a priority for the master branch, but should at least be dealt with for V4.

**Comment by mariehbourget** [comment]
> The output filename should not be hardcoded. I don't thinks it's a priority for the master branch, but should at least be dealt with for V4.

Definitely not a priority for master, the function is not used in the code (only in tests).

For V4, it seems that we will need it to create the "combined" mask. The naming should follow our naming convention with <image_name>_<axonmyelin_suffix>.png with the suffixes defined in https://github.com/neuropoly/axondeepseg/blob/master/config.py.

**Comment by mathieuboudreau** [comment]
Closing, was resolved in version 4.0: https://github.com/axondeepseg/axondeepseg/blame/a800e307cfab899a55d7d60db2719c6f29184a95/AxonDeepSeg/visualization/merge_masks.py#L21
