### ISSUE TITLE
Standardize use of `ads_utils.imread` in test files

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#564]
To read images, test files use interchangeably `imageio_imread` [(test_compute_morphometrics.py)](https://github.com/neuropoly/axondeepseg/blob/master/test/morphometrics/test_compute_morphometrics.py) and `ads_utils.imread` [(test_launch_morphometrics_computation.py)](https://github.com/neuropoly/axondeepseg/blob/master/test/morphometrics/test_launch_morphometrics_computation.py).

As pointed out by @mathieuboudreau, it would be beneficial for future work to centralize the calls to the image reader in `ads_utils`.

**Comment by mariehbourget** [comment]
Closing, fixed in #584.
