### ISSUE TITLE
Test all input options/combinations when running axondeepseg from terminal

### ISSUE THREAD

**Issue by alzaia** [axondeepseg/axondeepseg#57]
ref: https://github.com/neuropoly/axondeepseg/pull/52/files/286dc698db156e71a7271a25016a442e8e2de450#r170419632

**Comment by mathieuboudreau** [comment]
Done at some point in the past, CLI is included in the testing suites, eg

https://github.com/axondeepseg/axondeepseg/blob/58db2631bdba38e7a7dcda7a21bb164ea331c47b/test/test_segment.py#L266-L297
