### ISSUE TITLE
Various indentation throughout the code

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#58]
Examples of two different standards there:
https://github.com/neuropoly/axondeepseg/blob/e2e1fdc4ec07d5f66a2f9129670186540dbb4b38/AxonDeepSeg/train_network.py

and there:
https://github.com/neuropoly/axondeepseg/blob/e2e1fdc4ec07d5f66a2f9129670186540dbb4b38/AxonDeepSeg/segment.py

This needs to be harmonized, according to [this](https://www.python.org/dev/peps/pep-0008/#indentation).

**Comment by mathieuboudreau** [comment]
This was done broadly in the repo at one point, I recall a stagiere using [black](https://github.com/psf/black) to do this. We could rerun it prior to the next version release also maybe, I'll open an issue for that and add it to the to-do list
