### ISSUE TITLE
New feature: pixel units

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#597]
Add the option to set pixel units. Should be available on the command line and FSLeyes plugin.

**Comment by mariehbourget** [comment]
The supported pixel size units in ivadomed will be `mm`, `um` and `nm`, in compliance with BIDS.

Note that it is not yet implemented in ivadomed, but in-progress in https://github.com/ivadomed/ivadomed/pull/1025.

**Comment by mariehbourget** [comment]
The pixel size units feature is now available in ivadomed 2.9.4 and ADS with the merge of #612.

**Comment by mathieuboudreau** [comment]
Stale / was done in ivadomed at the time
