### ISSUE TITLE
Update models README and add link in documentation

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#599]
Following the release of version 4, the models were updated on their respective repos:
https://github.com/axondeepseg/default-SEM-model
https://github.com/axondeepseg/default-TEM-model
https://github.com/axondeepseg/default-BF-model

As discussed in meeting, we would like to update the README files with more information about training and usage of the models.
Example of another ivadomed model: https://github.com/ivadomed/model_seg_ms_mp2rage

When updated, we will also add the links to the repos in our documentation here: https://axondeepseg.readthedocs.io/en/latest/documentation.html#existing-models

**Comment by hermancollin** [comment]
Also, a good starting point for this issue would be to update the template here: https://github.com/neuropoly/axondeepseg/wiki/Template-for-Readme-of-new-models

**Comment by mariehbourget** [comment]
> I noticed the BF model lack a license file (other models have a MIT license). Is that intended?

Good catch, I don't think that is intended, @mathieuboudreau?

**Comment by hermancollin** [comment]
Now that the SEM model readme is merged, I updated both the TEM and BF ones. Also, the template is updated.

**Comment by hermancollin** [comment]
I added the version files in both the [TEM model repo](https://github.com/axondeepseg/default-TEM-model) and the [BF model repo](https://github.com/axondeepseg/default-BF-model). 

Also opened #621 to quickly add the repository links in the doc. Everything is ready for review/merge and then we can close this issue.
