### ISSUE TITLE
Update manual labelling instructions for ivadomed training pipeline

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#600]
In ADS version 4, we removed the documentation part about manual labelling from v3.3.0 here: https://axondeepseg.readthedocs.io/en/v3.3.0/documentation.html#manual-masks-for-training-your-own-model

We should update these instructions for the ivadomed pipeline and add them to the microcopy training tutorial.

**Comment by mathieuboudreau** [comment]
Stale - no longer using ivadomed
