### ISSUE TITLE
Fix weird filenames of data_axondeepseg_wakehealth_training dataset

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#605]
There is a problem with the filenames of this dataset. It will not pass the bids-validator and is inconsistent with the *data_axondeepseg_bf_training* dataset, which is very similar in terms of structure. When this dataset was originally created last summer, the ivadomed implementation into ADS was still in progress and the microscopy BEP as well. In order to train a model as fast as possible, some dirty fixes were used.

The problem originates from the fact that we obtained ROIs by manually cropping some samples and partial corrections from the *data_axondeepseg_wakehealth_source* dataset (*datasets/wakehealth* on git-annex). These files are named something like this:
> sub-42_sample-42_chunk-1_BF.tif

As we can see, the `chunk` entity is already used. Then, when we split this file in 4 sub-images, we need to identify these sub-files with an entity. Last summer, as a temporary solution, we went for something like this:
> sub-42_sample-42_chunk-1_desc-crop1_BF.tif

Here, we use the `desc` entity to assign an id to the cropped images. However, this entity is only available for derivative files or, as we figured out, for a derivative dataset. For more information about this, see https://github.com/ivadomed/ivadomed/issues/860. For now, the *data_axondeepseg_wakehealth_training* dataset type is set as derivative. I was able to train models on this data using this convention, but bids-validator will still fail here.

The problem is that we would ideally want to use the `chunk` entity to enumerate these cropped files, but by doing so, we are losing information about where the files came from because we have to overwrite the `chunk` field. Also, the `acq` entity might be more appropriate than the `desc` entity, like in the *data_axondeepseg_bf_training* dataset. A version of the wakehealth training set consistent with this aforementioned bf dataset is available on the `ac/consistent_with_bf_dataset` branch, which also uses the `acq` entity. On this branch, I overwrote the `chunk` entity, but the chunk information is still present in the `sourcedata` folder where I included the original files along with a README for more clarity. Note that this version passes the bids-validator test.

This issue was raised in #603

**Comment by mariehbourget** [comment]
Thank you @hermancollin for documenting this issue both here and in the dataset.
I'll try to look at the original issue https://github.com/ivadomed/ivadomed/issues/860 soon, and we'll make a plan!

**Comment by mariehbourget** [comment]
Hi @hermancollin, I'm starting to work on the "derivatives dataset" and "desc" entity again to try to clarify the situation.
Are you still using datasets with "desc" in filenames in your current experiments (wakehealth or other)?

**Comment by mariehbourget** [comment]
@hermancollin, I prepared some slides to better visualize the issue and move the discussion forward: https://docs.google.com/presentation/d/18mpdsBIDnvsBpseZQPpJkiWIiFPnn0QMz3Ni61wb6CI/edit#slide=id.g1858d416dfa_0_224

Feel free to add/comment on the slides, but no other action are required at this time.

**Comment by mariehbourget** [comment]
Sorry for the late update.

As discussed in 2022-11-11 meeting, we agreed that the best way to rename the files would be "suggestion" 1 from the slides, where we would use the "sample" entity to identify the ROI from the original NDPI and not used the "desc" entity.

@hermancollin, for the new batch of images we received, it may be confusing to use this "new" naming scheme just for these, so I would recommend keeping the "old" naming scheme for consistency, and maybe rename them all afterwards when the project is over? Anyway, this is just a suggestion, feel free to disregard and do what you deem best.

**Comment by mathieuboudreau** [comment]
Stale
