### ISSUE TITLE
Convert all "www.github.com/neuropoly/axondeepseg" links in repo to the new "www.github.com/axondeepseg/axondeepseg"

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#607]

**Comment by hermancollin** [comment]
Also we could pin the axondeepseg repo inside the organization (like here https://github.com/ivadomed)

**Comment by mathieuboudreau** [comment]
> Also we could pin the axondeepseg repo inside the organization (like here https://github.com/ivadomed)

Done. Didn't know about this feature, thanks!

**Comment by mathieuboudreau** [comment]
Closing, this was done.
