### ISSUE TITLE
Implement zoom factor sweep and segmentation auto-evaluation

### ISSUE THREAD

**Issue by mariehbourget** [axondeepseg/axondeepseg#610]
**Describe the problem**

When segmenting images than have a different resolution and/or axon sizes than the model resolution, we often have to try different pixel sizes to optimize the results, see #604 for example.

**Proposed solution**

In #609, we plan to add a new "zoom factor" option to the CLI that would multiply the pixel size, instead of changing the real pixel size itself.

In addition, we would like to explore the possibility of doing an "sweep" of different zoom factor in order to find automatically an optimal range or estimate for the zoom factor.

We would first need to define a metric to estimate the "best" zoom factor. For example: some sort of "ring" image identification (to find closed myelin), and then find the zoom factor that maximizes the number of rings.

**Comment by jcohenadad** [comment]
I *love* this idea!

**Comment by hermancollin** [comment]
To address this issue, the first part would be to implement the sweep feature. We can then later add on top a metric like discussed above.

Should it be an option for the main segmentation CLI or a separate script?

**Comment by mathieuboudreau** [comment]
I definitely think it should be an option in the main segmentation CLI, but could be written in a function outside of segment.py

**Comment by hermancollin** [comment]
The next part for this feature will be to train a classifier to evaluate the masks produced by the sweep. Here is my idea for the components of the training set:
- generate purposefully "bad" segmentations, i.e. the zoom factor is clearly not right for the input image and it produces incomplete/bad segmentations. Label these masks as ~0.2
- generate ok segmentations, i.e. the mask is not perfect but its what ADS can optimally achieve or close to it. Label these masks as ~0.8
- use some available manually corrected masks available from our datasets. Label these as 1 to show the model ideal cases. I happen to know that the TEM dataset contains more than 1.3 billion pixels of manually corrected masks, so we probably don't want to use everything as we need to keep some class balance. 

Then, we add the trained model to ADS and apply it to every segmentation produced by the sweep. It could then output the processed zoom factors ranked by the score the model gave them.

**Comment by mathieuboudreau** [comment]
Closing, implemented in https://github.com/axondeepseg/axondeepseg/pull/632

**Comment by hermancollin** [comment]
@mathieuboudreau thank you for the extensive cleanup you did last week. However I would like to keep this specific issue opened because the "metric" we were talking about is still not implemented. The sweep feature was only the first "easy" part but the mask evaluation we discussed could be an interesting internship project .

**Comment by mathieuboudreau** [comment]
Ok that makes sense. I closed it because the title and problem seemed to match up quite with what was done in that PR, so maybe while we're at it we could make the title a bit more specific to the "metric" in the title so that it's a bit more focused in on the internship project-aspect?

**Comment by mathieuboudreau** [comment]
Stale - no longer using zoom factor
