### ISSUE TITLE
Raise exception/notify user when the input image/pixel size does not lead to the minimum patch size

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#615]
See  #604 for an example where the user was provided a non user friendly error message for a case like this.

**Comment by hermancollin** [comment]
@mathieuboudreau well we could already compute the minimum pixel size and display it.
Also, maybe adding the resampled image size equation would provide more context.
`dimension of the image (in pixels) * pixel size (in microns/pixels) / resolution of the model (in microns/pixel) >= patch size (length_2D)`

**Comment by mathieuboudreau** [comment]
Yeah, but I think since the Zoom factor is already implemented for the FSLeyes add-on, it should be very quick to add it as a CLI addon and resolve that issue with this one together, as they are so closely related.
