### ISSUE TITLE
Add morphometrics flag for border touching axons

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#638]
**Describe the problem**
As discussed recently in #314, it would be useful to have an additional column in the morphometrics file that tells the user if an axon is touching the border of the image, mainly for easier cleanup when selecting fibers to keep in the analysis. The issue had already been raised by previous collaborators that wanted to remove partial axons, often located on the image border.

**Proposed solution**
very straightforward using `sklearn.measures.regionprops.bbox` and the image dimensions 

We have to wait for #636 to be merged first

**Comment by Stoyan-I-A** [comment]
Just FYI, my goal is to have #636 ready for review before next week
