### ISSUE TITLE
4.1 release

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#643]
Since the release of version 4 in february, we added features
- zoom factor option in #620 (merged)
- zoom factor sweep feature in #632
- logging feature in #633 

I suggest we release a new version when these last two are merged. For this, we need to merge #636 (morphometrics data structure refactoring) as well.
The main reason I created this issue is to remember to mention in the release notes that this version could slightly change the values obtained with the morphometrics script.

**Comment by hermancollin** [comment]
@mathieuboudreau yes we could release it. We could also wait for #647 to be closed by a PR before the release because this border-info feature will be more useful then.

**Comment by mathieuboudreau** [comment]
It sounds like the timing is right! Any chance we could resolve https://github.com/axondeepseg/axondeepseg/pull/642 prior in your view?

**Comment by mathieuboudreau** [comment]
Tagging @kousu since he might know more re: IVADOMED

**Comment by kousu** [comment]
Nothing to report! https://github.com/ivadomed/ivadomed/pull/1125 is still in progress and I know that's blocking https://github.com/axondeepseg/axondeepseg/pull/642 going in, but you can release without worrying about that going in yet, especially because you're pinned to the previous version of ivadomed anyway.

**Comment by hermancollin** [comment]
@mathieuboudreau I would suggest releasing our new minor version before #642 is merged because even when the ivadomed PR is complete, we will need to change the installation process a little bit and it would be nice to have a "stable" version before changing the installation section of the doc.

**Comment by hermancollin** [comment]
@mathieuboudreau we forgot about this but the blocking upstream ivadomed PR #1125 was merged. We kinda forgot about this but should we go forward with the 4.1 release?

**Comment by mathieuboudreau** [comment]
I think so; the fact that the GPU installation instructions were simplified between 4.0 and master means that the documentation is currently out-of-date if someone "downloads" the 4.0 version, per https://github.com/axondeepseg/axondeepseg/discussions/686
