### ISSUE TITLE
Pytest Error: "cannot import name 'console_main' " in GPU Cluster

### ISSUE THREAD

**Issue by Nish228** [axondeepseg/axondeepseg#649]
**Pytest Error**
On following the instructions given in the [Documentation](https://axondeepseg.readthedocs.io/en/latest/documentation.html#testing-the-installation)  of ADS for installation on the Rosenberg GPU cluster, I came across an error while running the comprehensive test.

**Error Description**

1. cd axondeepseg
2. "py.test --cov AxonDeepSeg/ --cov-report term-missing"

The error porduced is:
  File "/home/GRAMES.POLYMTL.CA/u119369/.conda/envs/ads_venv/bin/py.test", line 7, in <module>
    from pytest import console_main
ImportError: cannot import name 'console_main' from 'pytest' (/home/GRAMES.POLYMTL.CA/u119369/.local/lib/python3.8/site-packages/pytest/__init__.py)

**Suggestion**
The comprehensive test passed when the "pytest" in Step 2 was replaced with "python3 -m pytest". The modified command would be,
2. python3 -m py.test --cov AxonDeepSeg/ --cov-report term-missing

Another point to be made is that initially I assumed it was an OS-related error where I was mistaken that the error was during installation in CPU, but this error came when run on GPU. 

**Platform:**
 - GPU Cluster: Rosenberg 
 - OS: Ubuntu 20.04.4 LTS

**Comment by mathieuboudreau** [comment]
>ImportError: cannot import name 'console_main' from 'pytest' (/home/GRAMES.POLYMTL.CA/u119369/.local/lib/python3.8/site-packages/pytest/init.py)

@Nish228 it appears from this line that your environment is using the default Python package, and not a virtual environment. Are you sure you installed and activated the environment prior to running pytest?

**Comment by mathieuboudreau** [comment]
Ok thanks for that! 

So it appears that there is a conflict between the pytest version that pip is seeing:

>pytest==5.4.1


and that conda is seeing:

>pytest 7.1.2 py38h578d9bd_0 conda-forge


On my system, these two versions match.

I'm not sure how this could have happened, but I would suggest you open a new session (without your virtual environment activated), remove the "native" pytest installed in pip  (`pip uninstall`), delete your old conda virtual environment (`conda env remove -n ads_venv`), then create a brand new conda virtual environment using the ADS installation instructions. Activate it, do `pip install -e .` per usual,  then just try `pytest .` in the axondeepseg/ directory, and let me know how it goes now!

**Comment by Nish228** [comment]
@mathieuboudreau it works now!  I removed the native pytest installation and installed it again in ads_venv (using `pip install pytest`). Thank you so much!

**Comment by mathieuboudreau** [comment]
Great, thanks! Closing
