### ISSUE TITLE
Indexed image is flipped when loaded in FSLeyes

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#657]
This makes it difficult to know where the axons are for removal, because I can't read the ID numbers.

<img width="1440" alt="Screen Shot 2022-06-24 at 1 49 38 PM" src="https://user-images.githubusercontent.com/1421029/175606479-4053d239-6499-4c46-adf5-8bb3c3564ab1.png">

<img width="1272" alt="Screen Shot 2022-06-24 at 1 52 29 PM" src="https://user-images.githubusercontent.com/1421029/175606736-7b1bbe69-21e4-476d-97f1-015d32f3f1b1.png">

**Comment by Stoyan-I-A** [comment]
@mathieuboudreau By default, FSLeyes will flip L-R images (see [this comment](https://github.com/pauldmccarthy/fsleyes/issues/23#issuecomment-508956871) from Paul). However, if you open the ads_plugin, we remove the flip at the initialisation of the plugin. So just open the plugin and it should fix it.

**Comment by mathieuboudreau** [comment]
ahh I see. I have the plugin installed, but opened the image using the command line (i.e.`fsleyes image1.png image2.png`), I forgot to check if the plugin was loaded automatically or not. Thanks for clarifying, my bad!
