### ISSUE TITLE
Add additionnal logging sinks

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#664]
**Describe the problem**
I have been using the zoom factor sweep feature to process images and it is much quicker than before! However, it made me think of something @mathieuboudreau said when he reviewed #627. He wasn't sure if the current working directory was the best place to log the output.  

**Proposed solution**
For now, I would keep the log in the cwd, but we could add more sinks in specific situations:
- when the zoom factor sweep feature is used because it saves files in a subdirectory 
- also when the user provides an output folder, every script that saves files in there should ALSO log its console output inside this directory for future reference

Tell me what you think.

**Comment by mathieuboudreau** [comment]
@hermancollin this issue was open for the zoom factor, should this be still prioritized or closed?

**Comment by hermancollin** [comment]
I don't think this is worth investing a lot of time, it might get complicated.
