### ISSUE TITLE
Remove duplicated code in segment.py

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#67]
[This script](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/segment.py) has a lot of duplicated code between [segment_image](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/segment.py#L30) and [segment_folder](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/segment.py#L104).

a more elegant way would be to call `segment_image` inside `segment_folder`.

**Comment by mathieuboudreau** [comment]
Done, 

https://github.com/axondeepseg/axondeepseg/blob/58db2631bdba38e7a7dcda7a21bb164ea331c47b/AxonDeepSeg/segment.py#L196
