### ISSUE TITLE
'fsleyes' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by GrimmSnark** [axondeepseg/axondeepseg#672]
**Describe the bug**
Hello,

So I recently got a beefier computer for a number of tasks in the lab. One of which is running axondeepseg/ivadomed. I just installed a fresh version of anaconda and axondeepseg. It passes the axondeepseg_test script. However, when I try to load fsleyes I get :

`'fsleyes' is not recognized as an internal or external command `

Any help would be appreciated. 

**Platform (please complete the following information):**
 - OS: Win 10
 - AxonDeepSeg version number - 4.0.0

Best,

Michael

**Comment by mathieuboudreau** [comment]
Hi Michael,

As mentionned in our installation documentation (https://axondeepseg.readthedocs.io/en/latest/documentation.html#install-axondeepseg), the external software FSLeyes does not support the Windows operating system:

<img width="749" alt="Screen Shot 2022-08-03 at 12 12 27 PM" src="https://user-images.githubusercontent.com/1421029/182644221-043bc5a3-409c-45e4-8913-10dfdc4c748e.png">

As your tests all pass, you can still use AxonDeepSeg to segment images and produce morphometrics files using the command line tools: 

https://axondeepseg.readthedocs.io/en/latest/documentation.html#segmentation

https://axondeepseg.readthedocs.io/en/latest/documentation.html#morphometrics

If you want to use the plugin we created for graphical user interface that FSLeyes offers on that computer, you'll need to create a Linux virtual machine that runs in it; you can look up the tool VirtualBox and some pre-made images for it that are available online.

**Comment by Stoyan-I-A** [comment]
Alternatively, it is possible to run FSLeyes on Windows using the [Linux subsystem for Windows](https://docs.microsoft.com/en-us/windows/wsl/).
That being said, we don't have instructions at the moment on how to install it so you will have to figure it out on your own.

**Comment by mathieuboudreau** [comment]
Seems like FSL wrote up some documentation on this: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Windows#Windows_Subsystem_for_Linux

**Comment by GrimmSnark** [comment]
Hello,

Thank you again for your quick replies. I think I had looked at that webpage so much recently that I completely glossed over the warning box. 

Anyway, thanks again!

Michael
