### ISSUE TITLE
Leverage "no patch" option soon to be released in IVADOMED

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#676]
IVADOMED currently has a new feature (though not released in a pip version yet) that allows segmenting an image without patching during this step, which could resolve issues we occasionally encounter related to cutting the images in patches (eg straight lines that cut through the image masks).

There remains questions about what we'll want the default behaviour to be, because this is a memory intensive feature (not all computers will have suffiient RAM to work on images larger than a certain size, and this will vary between users).

We'll also need to test this feature vs our current behaviour on a range of test images (eg diffferent models, different axon sizes).

**Comment by mariehbourget** [comment]
Cross-referencing the ivadomed PR that implemented the feature: https://github.com/ivadomed/ivadomed/pull/1101
We should have a new PyPI release of ivadomed next week so we can move forward with this issue.

**Comment by mariehbourget** [comment]
ivadomed v2.9.7 was released and integrated in ADS in #693.
