### ISSUE TITLE
Prepare support for 3-class segmentation

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#698]
In order to support 3-class segmentation (context: unmyelinated fibers), we will need to change some stuff on the ADS side. For ivadomed, nothing really changes: we will use 3 ground-truths in the BIDS derivatives and change the training config accordingly. However, in ADS we will need to add some flexibility, notably:
- For the segmentation process, `axon_segmentation(...)` will need to also save the third prediction. Maybe also add flexibility to the `merge_masks(...)` if we want to support it: https://github.com/axondeepseg/axondeepseg/blob/821074c2c8b539bcec69686cce72304656124d51/AxonDeepSeg/apply_model.py#L46-L50
Not exactly sure how we would handle the 3rd class using grayscale format in the combined prediction image though
- Most of the work will probably be on the morphometrics process. Thanks to @Stoyan-I-A's refactoring, this should be easier to do because I think we will need to add columns for the 3rd class metrics (e.g. area, etc.). Fortunately, processing unmyelinated axons should be the exact same as processing axons. I'm thinking of adding a parameter to `get_axon_morphometrics(...)` indicating if we want 3-class morphometrics, and if so will load the 3rd segmentation and run the usual axon metrics on it. Not sure how we could merge this data in the morphometrics file (because the "myelin" columns will not apply to unmyelinated axons). In that case, maybe we would need 2 separate morphometrics file, but I don't really like that idea.

**Comment by mariehbourget** [comment]
> * Not exactly sure how we would handle the 3rd class using grayscale format in the combined prediction image though

That's a great point, we could add flexibility in merge mask by assigning the value based on the number of class, ex:
* 2 class = 127 and 255
* 3 class = 85, 170 and 255

Also, we have to take in consideration how fsleyes loads the mask overlays, as discussed in the ADS meeting last week, I believe it is hardcoded with fixed values and only for 2 class segmentation at the moment.

**Comment by mathieuboudreau** [comment]
>3 class = 85, 170 and 255

Why don't we just use the old values (127 and 255) for consistency between myelin and axon (and because these will be generated by ADS in the "first draft" segmentation), and add an intermediate value (eg 65 or 200) for the third axon class (whichever is closer to axon, I can't remember).

**Comment by mathieuboudreau** [comment]
The values don't really matter as far as I understand it except for them to be visually "contrasting"; they get separated to 0s and 1s later on in the code anyways right when we "separate" the masks.

**Comment by mariehbourget** [comment]
> Why don't we just use the old values (127 and 255) for consistency between myelin and axon (and because these will be generated by ADS in the "first draft" segmentation), and add an intermediate value (eg 65 or 200) for the third axon class (whichever is closer to axon, I can't remember).

Yes of course, that would be cleaner, you're right.
And probably easier to integrate in fsleyes to.

> The values don't really matter as far as I understand it except for them to be visually "contrasting"; they get separated to 0s and 1s later on in the code anyways right when we "separate" the masks.

* For ivadomed, it doesn't matter at all because we use separated masks with values 0 and 255 as input for each class.
* For ADS, yes we will need to check everywhere we "split" the mask to make sure it works as expected. Although, now that ADS (with ivadomed) writes separate masks anyway, we may want to revisit that and always use the separated masks.

**Comment by mathieuboudreau** [comment]
@hermancollin status/thoughts?

**Comment by hermancollin** [comment]
@mathieuboudreau we already have support for 3-class segmentation since #800. One of our model even outputs 5 classes. 

The way it works is that ADS reads the "config file" of the model, which specifies the nb of output classes with their name, and then saves the mask accordingly with suffix `[...]_seg-classname`.

We can also compute morphometrics for unmyelinated axons using the `-u` flag.
