### ISSUE TITLE
Idea: stop supporting combined axon-myelin images and switch to only separate

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#702]
This came up a couple of group meetings ago. If I recall, the reasoning behind it being that this is because it's how IVADOMED treats the images anyways, and would make things  simpler for the GUIs as well.

It wasn't clear to me if this was for both input and outputs of ADS; to me it makes sense to be only for inputs, as generating a combined axon-myelin image is still quite useful for us to look at. But it might make sense so stop supporint this combined image as an input into ADS. One potential issue I can see is that it might cause some issues if a user does manual correction of the separate masks on another software, as there might be overlapping pixels identified as both myelin and axon (something that is avoided by using the combined masks.

**Comment by hermancollin** [comment]
I agree that the redundancy is annoying but it's also very useful for quick-glance review of segmentations. I also think we should deprecate it, but keep the feature as an option. Maybe we could have an utility script that combines masks in a folder or something of the sort.

**Comment by mathieuboudreau** [comment]
I wasn't active in this discussion, it wasn't my idea per say, I was taking minutes and was tasked with opening this issue =) If I recall, @mariehbourget and @Stoyan-I-A with discussing this in the meeting, so they can maybe chime in and correct if I misunderstood anything! If no one is in huge favour of this at this time, we can close this issue.

**Comment by mariehbourget** [comment]
> I wasn't active in this discussion, it wasn't my idea per say, I was taking minutes and was tasked with opening this issue =) If I recall, @mariehbourget and @Stoyan-I-A with discussing this in the meeting,

If I recall correctly, the discussion was about how to load axon/myelin masks in fsleyes.
Currently, the loading is done with the merged mask with 127 (myelin) and 255 (axons) values. I think we were wondering if it would be possible/desirable to load each mask separately i.e. from the binary masks with values 0 (background) and 1 (axon or myelin).
This will become relevant if we choose to go with a third class for unmylinated axons (ref issue #698)

**Comment by mathieuboudreau** [comment]
Closing, dont think we're planning on doing this anymore
