### ISSUE TITLE
Scheduled CI fails irregularly on Windows (no-patch test)

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#706]
Over the holiday break I've received irregular emails stating that the CI has failed.

Here is the latest example: https://github.com/axondeepseg/axondeepseg/actions/runs/3826925769/jobs/6511100185#step:8:275

It occurs during the Windows matrix, for the test test/test_segment.py::TestCore::test_main_cli_runs_succesfully_with_nopatch_flag, which was merged from PR #696 

It doesn't occur consistently, i.e. I've rerun the tests and they sometimes pass.

The error is a segfault.

We've had this issue with Windows tests failing "randomly" before, they can be difficult to debug (maybe it's GitHub machine dependent?).

Nonetheless, having failing scheduled CI tests is not favourable, because we'll start ignoring them and the whole purpose of the scheduled CI tests are for us to be notified when something unexpected occurs with our code/dependencies on master, and so we might miss these.

@mariehbourget @kousu thoughts?

**Comment by mariehbourget** [comment]
> The error is a segfault.

If I'm not mistaken, segfault is a memory error.

It's also the same error I get with the new `--no-patch` option when there is not enough RAM to segment the image without patches on rosenberg (ref: #703)
So my guess is the image we try to segment is just in the limit of being too big for the no-patch option, and sometimes fails.
A workaround for the tests would be to change the pixel size (`-s` flag) to reduce the size of the image.

**Comment by mariehbourget** [comment]
For reference:

- The size of the test image is `436x344` with a pixel size of `0.37`.
- The pixel size of the model is `0.1`, so the final size of the image after resampling is `1614x1273` (so not that big).
- On my laptop, it took about 6 GB of RAM to segment the images without patches.

**Comment by mathieuboudreau** [comment]
Thanks for that info @mariehbourget !!!

As you suspected, the Windows (and linux) machines are riiiiight at the edge of those RAM requirements (7GB), and since Windows likely uses more RAM than Linux, this must be why it only fails on Windows.

<img width="556" alt="Screenshot 2023-01-03 at 10 45 37 AM" src="https://user-images.githubusercontent.com/1421029/210380211-d1706ce7-68e7-4664-bbfe-20834a33fe33.png">

**Comment by mariehbourget** [comment]
> Might there be a way to make this changes only when we detect a windows machine? I think it should be possible

I would suggest to change it for all tests as we only want to make sure the command runs smoothly and we don't care about the segmentation results.
We could change the pixel size to `0.1` for the 2 "no-patch" tests --> no resampling but still larger than a single 256x256 patch.
It would also avoid RAM issues and speed-up the tests.
We should add a comment in the test to document this to avoid confusion about the true pixel size in the future.

Alternatively, if we want to keep the "true" pixel size, we would need to add a smaller test image (crop) to the testing files.

**Comment by mathieuboudreau** [comment]
Ok! I'll take a crack at it and will add you as a reviewer for that PR!
