### ISSUE TITLE
Importing AxonDeepSeg.segment on its own creates an OpenMP error

### ISSUE THREAD

**Issue by Stoyan-I-A** [axondeepseg/axondeepseg#716]
**Describe the bug**
Importing `AxonDeepSeg/segment.py` on its own creates OpenMP an error. 
This does not happen when using the CLI functions that ADS provides.
It also does not happen when using the napari plugin (which does import `segment` at some point).
The error output links to the intel website, which might suggest that this issue is hardware dependent.

Here's the console output:
```
>>> import AxonDeepSeg.segment
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

**To Reproduce**

1. Open a terminal
2. Activate a conda environment where AxonDeepSeg is installed
3. Type `python` to start a python console
4. Type either `import AxonDeepSeg.segment` or `from AxonDeepSeg import segment`

**Platform:**
 - OS: Windows 10
 - Processor: Intel i7-8700

**Comment by Stoyan-I-A** [comment]
Typing
```
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
```
is a possible workaround.

**Comment by mathieuboudreau** [comment]
I tried on my mac and don't get an error; very likely a Windows-specific error since they do dynamic library linking differently/strangely if I recall correctly

**Comment by hermancollin** [comment]
Tried on my linux and the import works as well. Some people [here](https://stackoverflow.com/questions/64209238/error-15-initializing-libiomp5md-dll-but-found-libiomp5md-dll-already-initial?rq=1) suggest to reinstall numpy.

**Comment by Stoyan-I-A** [comment]
Updating numpy fixed my issue. Thanks @hermancollin!
It did warn my of some incompatible package with ivadomed when updating numpy but I had no problem running a model.

**Comment by Stoyan-I-A** [comment]
FYI this was the warning:
```
pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ivadomed 2.9.6 requires pyparsing<3,>=2.0.2, but you have pyparsing 3.0.9 which is incompatible.
```

**Comment by mathieuboudreau** [comment]
Ahh, and ivadomed is installed through pip and not conda, so version compatibilities aren't strictly enforced. that might be why
