### ISSUE TITLE
download_models could use a little makeover

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#717]
I was playing around with the `download_models` script and its behavior is not really ideal. For example, I found that #394 was still a problem (PR fixing it was closed for being stale). For context, the script downloads the model in the current working directory instead of the appropriate `AxonDeepSeg/models/` directory.

Also, in a fresh ADS install, the models are not downloaded at first. I think the reason we don't have any issue with users about this is that when the comprehensive tests are ran, the `download_models` script is tested so the models are downloaded at this step. I did a fresh install today and earlier in January and, without running the test suite, the only content of my *models* folder is this gibberish:
![Screenshot_20230203_134630](https://user-images.githubusercontent.com/83031821/216682832-6da8bd58-57d2-4bc8-8560-2feb55bee194.png)
I have no idea where this comes from, but the same content is present in both installations from today and from earlier in January.

At the end of the day, the fact that the models are not downloaded immediately after the installation would not be a problem if #394 was fixed.

**Comment by mathieuboudreau** [comment]
>Also, in a fresh ADS install, the models are not downloaded at first. I think the reason we don't have any issue with users about this is that when the comprehensive tests are ran, the download_models script is tested so the models are downloaded at this step. I did a fresh install today and earlier in January and, without running the test suite, the only content of my models folder is this gibberish:

I tried reproducing in a fresh install, and it works for me. I don't have those old TEM in the base models/ folder (which should be deleted, I agree), and the models are correctly downloaded in AxonDeepSeg/models/, see:

<img width="664" alt="Screenshot 2023-02-07 at 10 51 29 AM" src="https://user-images.githubusercontent.com/1421029/217294468-488c2935-f03c-404c-979e-7bf48f2d4391.png">

**Comment by mathieuboudreau** [comment]
Are you sure you did a fresh install (including a fresh `git clone`), or did you reuse your default AxonDeepSeg folder to do the installation? If the latter, those folders inside the models/ folder are likely ignored with the .gitignore, and might have been residue folders from usage a long time ago.

**Comment by mathieuboudreau** [comment]
>I have no idea where this comes from, but the same content is present in both installations from today and from earlier in January.

That's so weird, because I don't have them. Maybe try testing a fresh install using my #721 branch while reviewing, and see if the models/ folder gets created with them or if an error occurs because it is missing.

**Comment by hermancollin** [comment]
> Are you sure you did a fresh install (including a fresh `git clone`), or did you reuse your default AxonDeepSeg folder to do the installation? If the latter, those folders inside the models/ folder are likely ignored with the .gitignore, and might have been residue folders from usage a long time ago.

Hmm I think you are right on this one. I'm not sure I did a fresh git clone there.
