### ISSUE TITLE
Deprecated config_to_csv.py

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#718]
So I noticed we have this file right here: [models/config_to_csv.py](https://github.com/axondeepseg/axondeepseg/blob/ab28b4f506311c6ecc05adc69f056077278523da/models/config_to_csv.py). Am I mistaken or is this script 100% deprecated? It looks like it reads an earlier version of the config file.

**Comment by mathieuboudreau** [comment]
Yup - must of been a missed file that wasn't deleted when we moved to IVADOMED!
