### ISSUE TITLE
File pull_request_template.md contains a dead link

### ISSUE THREAD

**Issue by trallnag** [axondeepseg/axondeepseg#719]
This file: https://github.com/axondeepseg/axondeepseg/blob/ab28b4f506311c6ecc05adc69f056077278523da/.github/pull_request_template.md

It links to: https://www.neuro.polymtl.ca/software/contributing#pr_labels

Which is dead.

![image](https://user-images.githubusercontent.com/24834206/216765355-001a8f47-9a24-4cf8-89c0-53213f741e55.png)

**Comment by mathieuboudreau** [comment]
Thanks for informing us of this @trallnag ! 

The link has moved to https://intranet.neuro.polymtl.ca/geek-tips/contributing#pr-labels-a-href-pr-labels-id-pr-labels-a, I'll make the quick fix.
