### ISSUE TITLE
Implement pipeline for downsampled morphometrics maps for large scale microscopy

### ISSUE THREAD

**Issue by alzaia** [axondeepseg/axondeepseg#72]
When segmenting a large scale sample (e.g. full spinal cord slice), users need to obtain downsampled morphometrics maps. This can currently be done by the AxonSeg pipeline. The implementation of this functionality should also be available in AxonDeepSeg in order to remove the dependency with AxonSeg.

**Comment by mathieuboudreau** [comment]
Stale
