### ISSUE TITLE
Consider moving the config.py file inside the AxonDeepSeg directory.

### ISSUE THREAD

**Issue by Stoyan-I-A** [axondeepseg/axondeepseg#724]
Currently, the [config.py](https://github.com/axondeepseg/axondeepseg/blob/master/config.py) file is located outside the AxonDeepSeg directory.

This makes it so when we use it in a script, we will import it by typing
`import config` or `from config import <insert parameter you are trying to import>`.

The problem with this is that it makes it look like config file comes from outside of the ADS project.
An issue recently opened on the napari-plugin page (https://github.com/axondeepseg/napari-plugin/issues/4) is an example of how missleading this can be. If config.py was inside of the AxonDeepSeg directory, the error would have been something like `No module named 'AxonDeepSeg'` which would have been more clear that AxonDeepSeg might not be properly installed.

Moreover, we have the [AxonDeepSeg/params.py](https://github.com/axondeepseg/axondeepseg/blob/master/AxonDeepSeg/params.py) file which existed before `config.py` and serves a similar purpose.

Therefore, I suggest moving the content of `config.py` inside `params.py`

**Comment by mathieuboudreau** [comment]
I think this is a good idea - we should do this. I'm going to prioritize this, it should be quick
