### ISSUE TITLE
16 bit tifs not converted properly to 8 bit when images are loaded

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#737]
**Describe the bug**
From #736, this issue seems to have either not properly been fixed the last time(s) it came up, or has been reintroduced since then.

**To Reproduce**

Try loading a 16 bit image in Napari, and you'll see it doesn't appear correctly.

Image:

<img width="783" alt="Screenshot 2023-04-21 at 1 57 44 PM" src="https://user-images.githubusercontent.com/1421029/233693161-d6f8b62d-f97a-485c-bb4b-3fc330a10213.png">

Napari:

<img width="1376" alt="Screenshot 2023-04-21 at 1 58 46 PM" src="https://user-images.githubusercontent.com/1421029/233693192-e988cf2e-162c-4a35-8567-21d60dcb17c6.png">

Or also, try segmenting the 16bit image on the command line, and the output will not be what is expected.

Mask:

![Montage01-Tiled-crop-PS_seg-axonmyelin](https://user-images.githubusercontent.com/1421029/233693226-35a71848-7b5a-4db3-b1fb-287841510103.png)

And converting it manually to 8 bit in Gimp provides the expected results after re-running:

![Montage01-Tiled-crop-PS_8bit_seg-axonmyelin](https://user-images.githubusercontent.com/1421029/233693298-6b112af7-742b-4f9f-8420-c26d9baa23f0.png)

**Comment by Stoyan-I-A** [comment]
> Try loading a 16 bit image in Napari, and you'll see it doesn't appear correctly.

This is more likely a problem with Napari rather than ADS because the images are loaded using the Napari image loader.

**Comment by mathieuboudreau** [comment]
The segmentation probleem also occurs when simply running the CLI, so it may be both

**Comment by Stoyan-I-A** [comment]
Yeah the segmentation part is definitely an ADS problem. I was talking about the display on napari.

**Comment by mathieuboudreau** [comment]
@Stoyan-I-A mentioned in our meeting that the loading might be on the IVADOMED side, so I'll check and if so open an issue in IVADOMED and fix it there

**Comment by akraskovSMDB** [comment]
Hi @mariehbourget I had the same problem, reported in March, in the thread where the bug was supposedly fixed 
https://github.com/ivadomed/ivadomed/pull/1107#issuecomment-1463714960

**Comment by mathieuboudreau** [comment]
After a bit of exploring, I finally figured out the issue and likely solution.

The problem is on the IVADOMED, not ADS.

Using AxonDeepSeg's imread and imwrite, loading a 16b tif and then saving it to a png results in a good output image:

<img width="797" alt="Screenshot 2023-06-15 at 8 37 16 PM" src="https://github.com/axondeepseg/axondeepseg/assets/1421029/0764d3c2-622f-440c-bf05-b9f15894ce74">

IVADOMED doesn't have an easy API function call to read and write like ADS does, however finding the part in the code that deals with loading 2D (histology) images, https://github.com/ivadomed/ivadomed/blob/e101ebea632683d67deab3c50dd6b372207de2a9/ivadomed/loader/segmentation_pair.py#L316-L323, and executing the relevant line in a Python shell followed by saving the image to PNG using ADS's imwrite function, the output is cutoff:

<img width="797" alt="Screenshot 2023-06-15 at 8 40 46 PM" src="https://github.com/axondeepseg/axondeepseg/assets/1421029/07f1701a-cfc3-4854-8e92-24ffdb1e3926">

It's the `.astype(np.uint8)` call that's the culprit; it doesn't do the conversion correctly. Instead, replacing it with a `imageio.core.image_as_uint(raw_img, bitdepth=8)` conversion, the output then it good.

<img width="797" alt="Screenshot 2023-06-15 at 8 42 24 PM" src="https://github.com/axondeepseg/axondeepseg/assets/1421029/ca0483b3-2442-4d5a-bd73-679f4cf04069">

Even though IVADOMED is somewhat in a status-quo operating mode, I'll open a PR and since this is a quick fix, hopefully someone can review it and we can update our install of ivadomed to point to master so that we don't need to wait for a new release (which might never happen). This bug isn't something we can fix purely in the ADS side unfortunately.

**Comment by mathieuboudreau** [comment]
So the IVADOMED side (segmentation) of 16 bit images are fixed now with the latest version of IVADOMED, but napari doesn't show loaded 16b images properly still (see https://github.com/ivadomed/ivadomed/pull/1296#issuecomment-1850390124).

@Stoyan-I-A do you have an idea of what a good strategy for fixing this in napari would be?

**Comment by Stoyan-I-A** [comment]
@mathieuboudreau Do we have the 16 bit image sample? If the image is not displayed correctly in napari, regardless of whether or not the ADS plugin is loaded, then we should open an issue here : https://github.com/napari/napari
Or look if they already have one.

**Comment by mathieuboudreau** [comment]
Here's the 16 bit file: https://drive.google.com/file/d/1rNIvr-RtQnlidL1J3O96g_d1D22QsEW5/view?usp=sharing

It's too big to be shared here as an attachment.

I've quickly checked and didn't see any issue about viewer issues with 16 bit images

**Comment by Stoyan-I-A** [comment]
![image](https://github.com/axondeepseg/axondeepseg/assets/43790661/2ed95a40-6cba-45aa-b412-9a2ab04ede34)
Interestingly, google's viewer (left) also displays it darker compared to Windows' image viewer

**Comment by Stoyan-I-A** [comment]
Issue opened: https://github.com/napari/napari/issues/6534

**Comment by Stoyan-I-A** [comment]
The devs responded in the issue that it is a known bug and they have an open PR to fix it but 

> there is no consensus of proper solution

**Comment by mathieuboudreau** [comment]
Is there any way for us to "intercept"  images that are loaded so we can do a conversion to 8bit ourselves before it gets displayed? Or, add a button to load the image in our plugin which would then get passed along to the usual napari display/load?

**Comment by Stoyan-I-A** [comment]
> Is there any way for us to "intercept" images that are loaded so we can do a conversion to 8bit ourselves before it gets displayed?

I don't think we can for image formats that are already covered by napari.
napari does allow us to create reader plugins which allow to add new file formats to be read by the image loader. This can be useful if for exemple we want to add a way to read nifti files (in fact, someone [already did that](https://www.napari-hub.org/plugins/napari-nifti)). But I don't think this will work for file formats which napari already has readers for (e.i. most regular image types: png, jpg, tif & others).

> add a button to load the image in our plugin which would then get passed along to the usual napari display/load?

This is an option that would work. I would've preferred if the users could just use the built-in image loader, but this is easy to implement.

**Comment by mathieuboudreau** [comment]
>The problem is on the IVADOMED, not ADS.

This issue is stale, as we no longer use IVADOMED
