### ISSUE TITLE
Bug: Image loaded "as gray" deprecated

### ISSUE THREAD

**Issue by mathieuboudreau** [axondeepseg/axondeepseg#738]
**Describe the bug**
All the test suites are failing on GitHub CI as of yesterday due to a deprecated functionality of one of our dependencies, likely due to a new release.

Message: " TypeError: The keyword `as_gray` is no longer supported.Use `mode='L'` instead."

**Comment by Stoyan-I-A** [comment]
We use `as_gray` [here](https://github.com/axondeepseg/axondeepseg/blob/9888fc07f345e84563a2a292b005c1cbdf4e130d/AxonDeepSeg/ads_utils.py#L278) and [here](https://github.com/axondeepseg/axondeepseg/blob/9888fc07f345e84563a2a292b005c1cbdf4e130d/AxonDeepSeg/ads_utils.py#L282) (same file).

**Comment by mathieuboudreau** [comment]
I did all the chanced locally here: https://github.com/axondeepseg/axondeepseg/commit/15f78620674bec3aa178173a63827d1f95a7d2f8

But the error persists because IVADOMED also has some of those options set: https://github.com/ivadomed/ivadomed/issues/1291

So I think the quickest fix will be to fix the IVADOMED version to <2.28.0

**Comment by mathieuboudreau** [comment]
> We use `as_gray` [here](https://github.com/axondeepseg/axondeepseg/blob/9888fc07f345e84563a2a292b005c1cbdf4e130d/AxonDeepSeg/ads_utils.py#L278) and [here](https://github.com/axondeepseg/axondeepseg/blob/9888fc07f345e84563a2a292b005c1cbdf4e130d/AxonDeepSeg/ads_utils.py#L282) (same file).

We also used it explicitly in some tests as well, see my commit above. You could merge it in your branch, but I think the tests will still fail due to the IVADOMED side. I'm pushing a requirements quickfix for now
