### ISSUE TITLE
How to change pixel size in napari

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#747]
**Describe the problem**
When you load an image in napari and click on `Apply ADS model`, the user is prompted for the pixel size of the image. However, after this initial prompt, I don't think there is a way to change it. For example, if you load a new image and would like to use a different pixel size, there is no way to change it.

**Proposed solution**
Maybe some field where the user can change this value.

**Comment by mathieuboudreau** [comment]
How did we handle this in FSLeyes? I think if we changed images, it prompted us again, but I'm not 100% certain

**Comment by Stoyan-I-A** [comment]
> How did we handle this in FSLeyes?

We asked again.

The reason why this is different with napari is because in the napari plugin, it is added in the image's metadata. 

But if a new image is loaded and the pixel size file is not present, I expect it to prompt the user again. Otherwise it might be a bug. I'll have to check

**Comment by Stoyan-I-A** [comment]
>  if a new image is loaded and the pixel size file is not present, I expect it to prompt the user again. Otherwise it might be a bug.

I checked and the feature currently works as intended:
- If an image is loaded and the pixel size file is not present, a prompt will ask the user for the pixel size.
- If a new different image is loaded and the pixel size file is not present, it will prompt the user again.

Now, we can discuss if we want a way to change the pixel size but ideally the user would enter the correct pixel size and then adjust the zoom factor if needed.

**Comment by mathieuboudreau** [comment]
Is this still needed now @hermancollin, or has it become obsolete with the new models?
