### ISSUE TITLE
Create testimonials page

### ISSUE THREAD

**Issue by jcohenadad** [axondeepseg/axondeepseg#759]
Like in [SCT](https://spinalcordtoolbox.com/overview/testimonials.html), it would be great to create a testimonials page. Pros:
- it helps to get grants
- it helps attracting more users

[Here](https://docs.google.com/forms/d/e/1FAIpQLSdo6uzqlwO_H2XmUwzdAlMiOnpk7ui1jnEYlKrEBBh63GhfYQ/viewform) is the gform that was used for SCT. The link to the gform was kept on SCT website, we should do the same for ADS.

List of people we should ask testimonials from (please edit this list as we get more users):

- [x] - Alan Peterson
- [x] - Osvaldo Delbono
- [x] - Jacqueline Quandt
- [ ] - Brad Zuchero
- [x] - Anne Wheeler
- [x] - Ananya Gomatam
- [x] - [Eliana Lousada (junior) / Eric Burguiere (PI) / Christiane Schreiweis (PI)](https://www.mdpi.com/2076-3425/11/10/1353)
- [x] - [Alison Wong (junior) / Sami Tuffaha (PI)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0248323)

**Comment by mathieuboudreau** [comment]
Is there a preference between getting a testimonial from senior authors / PIs, or the lead author that actually used it?

**Comment by jcohenadad** [comment]
Preference from senior authors

**Comment by jcohenadad** [comment]
(I've edited the main issue above by adding a link to the gform used for SCT)

**Comment by mathieuboudreau** [comment]
>The link to the gform was kept on SCT website, we should do the same for ADS.

We don't have an AxonDeepSeg website; we could either keep somewhere in a GitHub markdown file (eg readme), or our ReadTheDocs site.

**Comment by jcohenadad** [comment]
i meant RTD (SCT's website is also RTD)

**Comment by mathieuboudreau** [comment]
I've made a form for ADS testimonials that has the same format as the SCT one: https://docs.google.com/forms/d/e/1FAIpQLSdEbhUKqJ775XHItPteq7Aa3LDOk790p_1tq9auo9xoYS32Ig/viewform?usp=sf_link

**Comment by mathieuboudreau** [comment]
Created a branch to add the Testimonials section, [ads/testimonials](https://github.com/axondeepseg/axondeepseg/tree/ads/testimonials) , and added a template text and testimonial to start with: https://axondeepseg.readthedocs.io/en/ads-testimonials/documentation.html#testimonials

**Comment by mathieuboudreau** [comment]
Drafted a email template: https://docs.google.com/document/d/1Ps642ZIqM28v6c0HYtTOEipf0ceoCi9MvNlEDg3K8VI/edit?usp=sharing


I've also switched the bulletpoint list of the authors in the issue description to a checklist, to keep track of who we've emailed or haven't yet.

**Comment by mathieuboudreau** [comment]
@hermancollin since you collaborated closely with Osvaldo, Brad, and Ananya, would you like to contact them about providing us with a testimonial? If you're too busy or not available, just let me know and I'll send the emails!

**Comment by hermancollin** [comment]
@mathieuboudreau ok I can take care of Osvaldo and Ananya. As for Brad, I'm not sure he used ADS but I'll be sure to mention it when we meet him (on wednesday presumably).

**Comment by hermancollin** [comment]
I sent the request to professor Delbono. As for Ananya, I would just want to confirm something. It seems the other emails were sent to PIs but Ananya was a student. I think she was in the same group as Charles Reiter from VCU. If this is a mistake, I think the person we want to contact is professor Geetanjali Bendale.

**Comment by mathieuboudreau** [comment]
> I sent the request to professor Delbono. As for Ananya, I would just want to confirm something. It seems the other emails were sent to PIs but Ananya was a student. I think she was in the same group as Charles Reiter from VCU. If this is a mistake, I think the person we want to contact is professor Geetanjali Bendale.

Seems like it to me too - I'd say email Gentajali first, and if we hear no response after about a week then we could try emailing Ananya.

**Comment by mathieuboudreau** [comment]
We've had two responses in the testimonial form, and I added them to the RTD branch - you can view them formatted here: https://axondeepseg.readthedocs.io/en/ads-testimonials/documentation.html#testimonials

I think we could merge it to master after getting a third testimonial, and then we'll just add them as we get them aftewards

**Comment by mathieuboudreau** [comment]
Resolved in #764
