### ISSUE TITLE
Segment nerve section to compute axon density

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#782]
Our collaborator wants to compute the axon density in his images. We have a shared OneDrive folder with him containing hundreds of images; segmentations and morphometrics are already computed. He wants to compute the axon density. To do so, we will train a model to segment the total nerve area per image. For example, the img below contains 5 fascicles. The mask we want will delimit the inner area **inside** the perineurium

![Nerve area](https://github.com/axondeepseg/axondeepseg/assets/83031821/b879603f-22c2-418f-ab6c-a5393049b9c8)

After this, we will be able to do 2 things:
- estimate axon density per image
- filter false positives located outside the nerve area

We will thus be able to compute a new metric for this data _and_ improve the current segmentation quality. Here is a somewhat exhaustive TODO list:
1. select ~30 images and start gathering annotations
2. send to Osvaldo and wait for feedback
3. train model (probably nnunet)
4. inference on all his data
5. approximate axon density: script to compute nerve area from the masks and read morphometrics CSVs

**Comment by hermancollin** [comment]
For future reference, this project is almost complete. More details on this repo: www.github.com/axondeepseg/model_seg_nerve

**Comment by hermancollin** [comment]
Update: our collaborator provided a lot of manual measurements so we will be able to accurately evaluate our method.

**Comment by mathieuboudreau** [comment]
>@hermancollin moved this from In Progress to Done in [NeuroPoly projects](https://github.com/orgs/neuropoly/projects/3) [on Aug 1](https://github.com/axondeepseg/axondeepseg/issues/782#event-14821397029)

If this is the case, can we close?

**Comment by hermancollin** [comment]
Yes. We had an intern who worked on this, but it didn't really lead anywhere and our collaborator ended up manually computing the nerve areas.
