### ISSUE TITLE
Fresh `git clone` is ~150MB due to large files in git history

### ISSUE THREAD

**Issue by joshuacwnewton** [axondeepseg/axondeepseg#793]
The repository source code is tiny (345kB zip), and the files on `master` aren't very large either.

Despite this, `git clone` takes quite a while:

```console
dot|joshua@monarch:~/repos$ git clone git@github.com:axondeepseg/axondeepseg.git
Cloning into 'axondeepseg'...
remote: Enumerating objects: 7206, done.
remote: Counting objects: 100% (1184/1184), done.
remote: Compressing objects: 100% (511/511), done.
remote: Total 7206 (delta 770), reused 996 (delta 652), pack-reused 6022
Receiving objects: 100% (7206/7206), 361.13 MiB | 6.54 MiB/s, done.
Resolving deltas: 100% (4896/4896), done.
```

Running this magic command on the ADS repo, I get:

```console
master|joshua@monarch:~/repos/axondeepseg$ git rev-list --objects --all |
  git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |
  sed -n 's/^blob //p' |
  sort --numeric-sort --key=2 |
  cut -c 1-12,41- |
  $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
[...]
fd191fadbc9f   18MiB AxonDeepSeg/models/default_TEM_model_v1/model.ckpt.data-00000-of-00001
518f4ce79b78   18MiB AxonDeepSeg/models/default_TEM_model_v1/model.ckpt.data-00000-of-00001
18c7902e2998   18MiB AxonDeepSeg/models/default_TEM_model_v1/model.hdf5
c022760ddc1a   18MiB AxonDeepSeg/models/default_TEM_model_v1/model.hdf5
f9a5cea84f1b   22MiB AxonDeepSeg/models/default_SEM_model_v1/model.ckpt.data-00000-of-00001
6d6405655f20   22MiB AxonDeepSeg/models/default_SEM_model_v1/model.ckpt.data-00000-of-00001
9a6a80accd6a   23MiB AxonDeepSeg/models/default_SEM_model_v1/model.hdf5
27d52e20b311   23MiB AxonDeepSeg/models/default_SEM_model_v1/model.hdf5
319f00ad01bc   75MiB __tmp__/model_seg_mouse_axon-myelin_tem/model_seg_mouse_axon-myelin_tem.onnx
677f343e4907   75MiB __tmp__/model_seg_rat_axon-myelin_sem/model_seg_rat_axon-myelin_sem.onnx
971645af70a2   75MiB __tmp__/model_seg_rat_axon-myelin_bf/model_seg_rat_axon-myelin_bf.onnx
dd4cb4d7b239   75MiB __tmp__/model_seg_mouse_axon-myelin_tem/model_seg_mouse_axon-myelin_tem.pt
9810546ee276   75MiB __tmp__/model_seg_rat_axon-myelin_sem/model_seg_rat_axon-myelin_sem.pt
2a42b19c5ab7   75MiB __tmp__/model_seg_rat_axon-myelin_bf/model_seg_rat_axon-myelin_bf.pt
```

We can use these blob hashes to identify relevant commits. For example:

```console
master|joshua@monarch:~/repos/axondeepseg$ git log --raw --all --find-object=2a42b19c5ab7b924cc2015b70230c677dc460c85
commit 408f7562c0f1e0cc3c578bca79db40ff06f92e7e
Author: Mathieu Boudreau <emb6150@gmail.com>
Date:   Fri Dec 8 12:42:08 2023 -0400

    Remove temp files

:100644 000000 2a42b19 0000000 D        __tmp__/model_seg_rat_axon-myelin_bf/model_seg_rat_axon-myelin_bf.pt

commit 442da343ed21f70eff24e86469a3948e7cf46be9
Author: Mathieu Boudreau <emb6150@gmail.com>
Date:   Fri Dec 8 12:41:03 2023 -0400

    Try editable pip install and commit instead of branch

:000000 100644 0000000 2a42b19 A        __tmp__/model_seg_rat_axon-myelin_bf/model_seg_rat_axon-myelin_bf.pt
```

The above commits belong to PR #739. The PR was merged using a squash commit, so `master` doesn't have the files. But, the associated branch ([`sia/738/image_loading_patch`](https://github.com/axondeepseg/axondeepseg/tree/sia/738/image_loading_patch)) wasn't deleted! 

I'd recommend going through the [currently open branches](https://github.com/axondeepseg/axondeepseg/branches/all) and deleting ones associated with merged PRs. This should speed up `git clones`.

**Comment by Stoyan-I-A** [comment]
Thank you @joshuacwnewton. I'll delete my old branches that aren't relevant anymore.
I invite the other devs to do so as well.

**Comment by mathieuboudreau** [comment]
Thanks @joshuacwnewton ! Yes we should really regularly check the stale branches, I'll set myself a monthly reminder to check that, also find a mechanism to remind the person that merges/opens a PR to delete the branch automatically after merging (maybe there's a default option for that?)

**Comment by mathieuboudreau** [comment]
Also, maybe a good idea to revisit #464, which was started to prevent the mistake I made in stoyan's branch of accidentally pushing large files. @joshuacwnewton do you guys have an implementation of this sort for SCT?

**Comment by mathieuboudreau** [comment]
Cleaning up the branches cut down the repo size by slightly more than half:

```

(base) mathieuboudreau@Mathieus-MacBook-Pro cleanup % git clone https://github.com/axondeepseg/axondeepseg.git
Cloning into 'axondeepseg'...
remote: Enumerating objects: 6130, done.
remote: Counting objects: 100% (754/754), done.
remote: Compressing objects: 100% (349/349), done.
Receiving objects: 100% (6130/6130), 150.31 MiB | 462.00 KiB/s, done.
remote: Total 6130 (delta 524), reused 554 (delta 394), pack-reused 5376
Resolving deltas: 100% (4178/4178), done.
(base) mathieuboudreau@Mathieus-MacBook-Pro cleanup % 
```

Beyond that, we'd have to use BFG repo cleaner on files from the main branch or rebase main, because now most of the big files are from some of the models that we used to host here instead of in another repo (and update regularly :/), but then we'd lose a lot of our history / ability to reproduce old versions. I don't think that's a good idea, unless we'd clone and archive ADS and it's current history in another repo, and then rebase this one, which I think we'd have to think about the pros and cons for a while. @joshuacwnewton do you have additional thoughts ideas?

**Comment by mathieuboudreau** [comment]
Another thing we could do is for *users*, give them instructions in our docs to clone with a depth of 1, that should speed things up for them at least!

**Comment by joshuacwnewton** [comment]
> Beyond that, we'd have to use BFG repo cleaner on files from the main branch or rebase main, because now most of the big files are from some of the models that we used to host here instead of in another repo (and update regularly :/), but then we'd lose a lot of our history / ability to reproduce old versions. I don't think that's a good idea, unless we'd clone and archive ADS and it's current history in another repo, and then rebase this one, which I think we'd have to think about the pros and cons for a while. @joshuacwnewton do you have additional thoughts ideas?

I think your assessment is fair! SCT has tried to prune large files in the past as well, and we also settled on a combination of "backup repo" (https://github.com/spinalcordtoolbox/spinalcordtoolbox-dev) + BFG (https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/1823).

I think ~150MB is a fine size to pause at for now? You've handled the "low hanging fruit", and at this point the benefit may not be significant enough to be worth the effort.

**Comment by joshuacwnewton** [comment]
> Also, maybe a good idea to revisit #464, which was started to prevent the mistake I made in stoyan's branch of accidentally pushing large files. @joshuacwnewton do you guys have an implementation of this sort for SCT?

Not yet! This is a WIP for us as well: https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/2705

Though, I've personally had a renewed interest in git hooks recently (see https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4399, as well as https://github.com/joshuacwnewton/dotfiles/tree/dot/.githooks), so I could see getting around to this soon? It would be nice to set aside an afternoon to come up with something that could benefit the lab as a whole.

**Comment by mathieuboudreau** [comment]
@joshuacwnewton just discovered that Github now has this option: https://github.blog/changelog/2024-04-18-push-rules-public-beta/
