### ISSUE TITLE
video not embedded in GUI section of documentation

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#823]
**Describe the bug**

the video embedding failed and there's an hyperlink that's not formatted correctly.
![Screenshot_20240920_151352](https://github.com/user-attachments/assets/c7644257-3813-4fbc-8456-f33a56d638c5)

Maybe something introduced in #800 that we missed? I checked and it looks like the only place where there's a problem.

**Comment by mathieuboudreau** [comment]
Nice catch @hermancollin  - unsure also how this got introduced, but #825 should resolve it
