### ISSUE TITLE
default target dir of `download_model` not checked

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/axondeepseg#835]
https://github.com/axondeepseg/axondeepseg/blob/7b79f486f731dfa05f9fbfab1a24e4710a652c9b/AxonDeepSeg/download_model.py#L11-L20

I just called `download_model` outside of the _axondeepseg_ root directory. It just created a folder called _AxonDeepSeg/models/modelname_ in my cwd. Maybe the default directory should be infered based on the script location? Something like this:

```python
base_path = Path(__file__).parent.resolve()
model_destination = base_path / 'models' / full_model_name 
```

**Comment by mathieuboudreau** [comment]
I can handle this @hermancollin unless you're already preparing a PR

**Comment by hermancollin** [comment]
@mathieuboudreau nope you can go ahead
